const pool = require('../config/database');

let ensurePromise = null;

const ensureRevenueAllocationTable = async () => {
    if (!ensurePromise) {
        ensurePromise = (async () => {
            await pool.query(
                `CREATE TABLE IF NOT EXISTS shipment_revenue_allocations (
                    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    shipment_id         INT NOT NULL REFERENCES order_shipments(id) ON DELETE CASCADE,
                    driver_id           INT NOT NULL REFERENCES profiles(id),
                    share_percent       NUMERIC(5,2) NOT NULL CHECK (share_percent > 0 AND share_percent <= 100),
                    allocation_reason   TEXT NOT NULL
                                            CHECK (allocation_reason IN (
                                                'default_owner',
                                                'incident_full_transfer',
                                                'incident_split'
                                            )),
                    incident_id         INT REFERENCES incidents(id) ON DELETE SET NULL,
                    created_by          INT REFERENCES profiles(id),
                    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    UNIQUE (shipment_id, driver_id)
                )`,
            );
            await pool.query(
                'CREATE INDEX IF NOT EXISTS idx_rev_alloc_shipment ON shipment_revenue_allocations(shipment_id)',
            );
            await pool.query(
                'CREATE INDEX IF NOT EXISTS idx_rev_alloc_driver ON shipment_revenue_allocations(driver_id)',
            );
        })().catch((error) => {
            ensurePromise = null;
            throw error;
        });
    }

    return ensurePromise;
};

const replaceShipmentAllocations = async (
    client,
    shipmentId,
    allocations,
    { allocationReason, incidentId = null, createdBy = null } = {},
) => {
    await ensureRevenueAllocationTable();

    if (!Array.isArray(allocations) || allocations.length === 0) {
        throw new Error('Revenue allocation list cannot be empty');
    }

    const totalShare = allocations.reduce((sum, allocation) => sum + Number(allocation.sharePercent || 0), 0);
    if (Math.abs(totalShare - 100) > 0.001) {
        throw new Error('Revenue allocations must sum to 100%');
    }

    await client.query(
        'DELETE FROM shipment_revenue_allocations WHERE shipment_id = $1',
        [shipmentId],
    );

    for (const allocation of allocations) {
        await client.query(
            `INSERT INTO shipment_revenue_allocations
                (shipment_id, driver_id, share_percent, allocation_reason, incident_id, created_by, created_at)
             VALUES ($1, $2, $3, $4, $5, $6, NOW())`,
            [
                shipmentId,
                allocation.driverId,
                Number(allocation.sharePercent),
                allocationReason,
                incidentId,
                createdBy,
            ],
        );
    }
};

const getDriverIdsForShipment = async (shipmentId, fallbackDriverId = null) => {
    await ensureRevenueAllocationTable();

    const result = await pool.query(
        `SELECT driver_id
         FROM shipment_revenue_allocations
         WHERE shipment_id = $1
         ORDER BY driver_id ASC`,
        [shipmentId],
    );

    const ids = result.rows.map((row) => Number(row.driver_id)).filter(Boolean);
    if (ids.length > 0) {
        return [...new Set(ids)];
    }

    return fallbackDriverId ? [Number(fallbackDriverId)] : [];
};

module.exports = {
    ensureRevenueAllocationTable,
    replaceShipmentAllocations,
    getDriverIdsForShipment,
};
