-- =====================================================================
-- 20260902_reversal_requests
-- Yêu cầu hoàn tác tầng 2: người làm sai xin lùi, người có quyền duyệt.
--
-- Vì sao cần: các thao tác tầng 2 (gỡ duyệt chi phí, huỷ xác nhận khoản nộp, gỡ
-- hoàn thành chuyến) hiện ai có quyền là tự làm tự lùi. Nếu chính người bấm nhầm
-- tự gỡ thì không ai biết chuyện gì đã xảy ra — mà đó đúng là chỗ dễ bị lạm dụng
-- nhất, vì các thao tác này đều đụng tới tiền.
--
-- Bảng này KHÔNG thực hiện việc lùi. Nó chỉ ghi lại "ai xin lùi cái gì, vì sao, ai
-- quyết, quyết lúc nào". Việc lùi vẫn do đúng service nghiệp vụ làm, vì chỉ nó biết
-- phải dọn những gì kèm theo.
--
-- An toàn với dữ liệu cũ: bảng mới hoàn toàn, không đụng bảng nào đang có.
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS reversal_requests (
    id           INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,

    -- Khoá trong sổ đăng ký của reversalService, vd 'expense.approve'. Cố ý để TEXT
    -- không ràng buộc CHECK: thêm một loại thao tác lùi là việc của mã nguồn, không
    -- nên phải chạy migration. Mã đã từ chối khoá lạ ngay ở cửa vào (spec()).
    kind         TEXT NOT NULL,
    entity_type  TEXT NOT NULL,
    entity_id    INT  NOT NULL,

    reason       TEXT NOT NULL CHECK (btrim(reason) <> ''),
    requested_by INT  NOT NULL REFERENCES profiles(id),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    status       TEXT NOT NULL DEFAULT 'pending'
                     CHECK (status IN ('pending', 'approved', 'rejected', 'cancelled')),

    decided_by     INT REFERENCES profiles(id),
    decided_at     TIMESTAMPTZ,
    decision_note  TEXT,

    -- Kết quả thực thi sau khi duyệt. Tách khỏi status vì "đã duyệt" và "đã lùi xong"
    -- là hai việc: duyệt xong mà service nghiệp vụ từ chối (khoản đã chi mất rồi) thì
    -- yêu cầu vẫn approved nhưng không có gì được lùi — phải nhìn thấy được điều đó.
    executed_at    TIMESTAMPTZ,
    execution_error TEXT,

    CONSTRAINT reversal_requests_decided_together CHECK (
        (status = 'pending' AND decided_by IS NULL AND decided_at IS NULL)
        OR (status <> 'pending' AND decided_by IS NOT NULL AND decided_at IS NOT NULL)
    )
);

-- Một đối tượng chỉ được có MỘT yêu cầu đang chờ. Không có ràng buộc này thì tài xế
-- bấm xin lùi năm lần vì sốt ruột, và điều phối thấy năm dòng giống hệt nhau.
CREATE UNIQUE INDEX IF NOT EXISTS uq_reversal_requests_pending
    ON reversal_requests (entity_type, entity_id)
    WHERE status = 'pending';

-- Màn duyệt luôn mở ở "đang chờ, cũ nhất trước"
CREATE INDEX IF NOT EXISTS idx_reversal_requests_pending
    ON reversal_requests (status, requested_at)
    WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_reversal_requests_requester
    ON reversal_requests (requested_by, requested_at DESC);

INSERT INTO schema_migrations (filename)
VALUES ('20260902_reversal_requests.sql')
ON CONFLICT (filename) DO NOTHING;

COMMIT;
