-- =====================================================================
-- 20260830_receipt_ai_validation
-- Nền cho lớp kiểm tra hóa đơn bằng trích xuất có cấu trúc.
--
-- Lớp OCR cũ chỉ dò ra một con số rồi so với số khai trong dung sai 15%, nên bất kỳ
-- ảnh nào có một con số cũng qua được. Ba việc thật sự cần làm — xác nhận đúng là hóa
-- đơn, xác nhận hàng/dịch vụ thuộc bảo dưỡng, và cộng lại số lượng × đơn giá — đều cần
-- CẤU TRÚC của tờ hóa đơn, thứ mà text phẳng của Tesseract đã làm mất.
--
-- Hai bảng ở đây phục vụ hai việc khác nhau:
--   * maintenance_item_keywords — từ điển hạng mục để phân loại từng dòng hàng. Danh
--     sách gốc nằm trong code (services/receiptTaxonomy.js); bảng này chỉ chứa phần
--     THÊM/ĐÈ, để quản lý duyệt tay xong là từ điển lớn lên mà không cần deploy.
--   * receipt_extractions — lưu vết nguyên văn model đọc được + kết quả từng kiểm tra.
--     Cần cho tranh chấp (có bản gốc để đối chiếu), cho việc đo độ chính xác thật, và
--     cho vòng phản hồi khi quản lý ghi đè phán quyết của máy.
--
-- An toàn với dữ liệu cũ: chỉ tạo bảng mới, không đụng bảng nào đang có.
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS maintenance_item_keywords (
    id          INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,

    -- Đã chuẩn hoá: bỏ dấu, chữ thường, gộp khoảng trắng. Việc chuẩn hoá do code làm
    -- (receiptTaxonomy.normalize) — lưu sẵn dạng chuẩn để so khớp không phải xử lý lại.
    keyword     TEXT NOT NULL UNIQUE,
    category    TEXT NOT NULL,
    item_group  TEXT NOT NULL CHECK (item_group IN ('maintenance', 'excluded')),

    source      TEXT NOT NULL DEFAULT 'manual'
                    CHECK (source IN ('manual', 'learned')),
    created_by  INT REFERENCES profiles(id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE maintenance_item_keywords IS
    'Phần MỞ RỘNG của từ điển hạng mục bảo dưỡng. Danh sách gốc ở services/receiptTaxonomy.js; bảng này để nuôi thêm từ khoá lúc chạy mà không cần deploy.';
COMMENT ON COLUMN maintenance_item_keywords.source IS
    'manual = người nhập tay; learned = sinh ra từ lần quản lý sửa phân loại của máy.';

CREATE TABLE IF NOT EXISTS receipt_extractions (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,

    entity_type     TEXT NOT NULL CHECK (entity_type IN ('maintenance_record', 'expense')),
    entity_id       INT,

    image_url       TEXT NOT NULL,
    -- Băm nội dung ảnh. Dùng cho việc chặn nộp lại đúng một tấm ảnh (giai đoạn 2);
    -- tính sẵn từ bây giờ vì extractor đã phải tải ảnh về rồi, không tốn thêm gì.
    image_sha256    TEXT,

    provider        TEXT,
    model           TEXT,
    prompt_version  TEXT,

    -- Nguyên văn JSON model trả về, KHÔNG chỉnh sửa. Khi tranh chấp thì đây là bằng
    -- chứng máy đã đọc được gì, tách bạch với phán quyết do code đưa ra.
    raw_extraction  JSONB,
    checks          JSONB NOT NULL DEFAULT '[]'::jsonb,

    verdict         TEXT NOT NULL
                        CHECK (verdict IN ('passed', 'needs_review', 'rejected', 'error')),

    claimed_amount  NUMERIC(12,2),
    receipt_total   NUMERIC(12,2),
    latency_ms      INT,

    -- Quản lý đồng ý hay ghi đè. Ghi đè là tín hiệu máy sai — chính là dữ liệu để
    -- bổ sung từ điển và để báo cáo độ chính xác thật.
    reviewed_by     INT REFERENCES profiles(id),
    review_action   TEXT CHECK (review_action IN ('agree', 'override_accept', 'override_reject')),
    review_note     TEXT,
    reviewed_at     TIMESTAMPTZ,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_receipt_extractions_entity
    ON receipt_extractions (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_receipt_extractions_hash
    ON receipt_extractions (image_sha256) WHERE image_sha256 IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_receipt_extractions_verdict
    ON receipt_extractions (verdict, created_at DESC);

INSERT INTO schema_migrations (filename)
VALUES ('20260830_receipt_ai_validation.sql')
ON CONFLICT (filename) DO NOTHING;

COMMIT;
