/**
 * Ca kiểm thử CHẶN QUYỀN — gom theo CONTROLLER, không theo file route.
 *
 * Một file route có thể gọi nhiều controller (tripRoutes.js gọi cả tripController lẫn
 * paymentController), nên nếu gom theo file route thì một sheet báo cáo sẽ lấy dòng từ
 * nhiều file test và ngược lại. Gom theo controller giữ đúng quy ước 1 file test = 1 sheet.
 *
 * Sinh tự động từ backend/routes/*.js — đừng sửa tay, sửa route rồi chạy lại bộ sinh.
 */

module.exports = {
    AccountantBankTransfer: [
        {
            method: 'GET',
            path: '/accountant/receipts/bank-transfer',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/receipts/bank-transfer route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/accountant/receipts/100000/confirm-bank-transfer',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only POST /accountant/receipts/100000/confirm-bank-transfer route before controller logic runs',
        },
    ],
    AccountantDebtController: [
        {
            method: 'GET',
            path: '/accountant/debts',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/debts route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/debts/stats',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/debts/stats route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/debts/grouped',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/debts/grouped route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/debts/person/driver/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/debts/person/driver/100000 route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/debts/owners',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/debts/owners route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/accountant/debts/manual',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only POST /accountant/debts/manual route before controller logic runs',
        },
        {
            method: 'PUT',
            path: '/accountant/debts/manual/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only PUT /accountant/debts/manual/100000 route before controller logic runs',
        },
        {
            method: 'DELETE',
            path: '/accountant/debts/manual/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only DELETE /accountant/debts/manual/100000 route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/accountant/debts/100000/transfer-to-driver',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only POST /accountant/debts/100000/transfer-to-driver route before controller logic runs',
        },
    ],
    AccountantLedgerController: [
        {
            method: 'GET',
            path: '/accountant/ledger',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/ledger route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/ledger/stats',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/ledger/stats route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/accountant/ledger/export',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only POST /accountant/ledger/export route before controller logic runs',
        },
    ],
    AccountantOrderController: [
        {
            method: 'GET',
            path: '/accountant/orders/lookup',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/orders/lookup route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/orders/partners',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/orders/partners route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/orders/customer-by-phone',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/orders/customer-by-phone route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/orders/export',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/orders/export route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/orders',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/orders route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/accountant/orders',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only POST /accountant/orders route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/accountant/orders/import/preview',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only POST /accountant/orders/import/preview route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/accountant/orders/import',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only POST /accountant/orders/import route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/orders/100000/shipments',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/orders/100000/shipments route before controller logic runs',
        },
        {
            method: 'PUT',
            path: '/accountant/orders/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only PUT /accountant/orders/100000 route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/accountant/orders/100000/shipments/100000/driver-payment',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only POST /accountant/orders/100000/shipments/100000/driver-payment route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/orders/100000/customer-debt',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/orders/100000/customer-debt route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/orders/100000/payments',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/orders/100000/payments route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/accountant/orders/100000/payments',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only POST /accountant/orders/100000/payments route before controller logic runs',
        },
    ],
    AccountantPaymentController: [
        {
            method: 'GET',
            path: '/accountant/debts/payment/history',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/debts/payment/history route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/debts/payment/history/driver/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/debts/payment/history/driver/100000 route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/accountant/debts/payment/preview',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only POST /accountant/debts/payment/preview route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/accountant/debts/payment/allocate',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only POST /accountant/debts/payment/allocate route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/accountant/debts/payment/by-shipment',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only POST /accountant/debts/payment/by-shipment route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/accountant/debts/payment/by-debt',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only POST /accountant/debts/payment/by-debt route before controller logic runs',
        },
    ],
    AccountantPayrollController: [
        {
            method: 'GET',
            path: '/accountant/payroll/advances',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/payroll/advances route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/accountant/payroll/advances/100000/disburse',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only PATCH /accountant/payroll/advances/100000/disburse route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/accountant/payroll/generate',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only POST /accountant/payroll/generate route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/payroll',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/payroll route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/accountant/payroll/100000/confirm',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only PATCH /accountant/payroll/100000/confirm route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/accountant/payroll/100000/pay',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only PATCH /accountant/payroll/100000/pay route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/accountant/payroll/100000/revert',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only PATCH /accountant/payroll/100000/revert route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/accountant/payroll/100000/adjust',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only PATCH /accountant/payroll/100000/adjust route before controller logic runs',
        },
    ],
    AccountantReportController: [
        {
            method: 'GET',
            path: '/accountant/reports/overview',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/reports/overview route before controller logic runs',
        },
    ],
    AdminController: [
        {
            method: 'POST',
            path: '/api/admin/users',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only admin user route POST /api/admin/users route before controller logic runs',
        },
        {
            method: 'PUT',
            path: '/api/admin/users/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only admin user route PUT /api/admin/users/100000 route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/admin/users/100000/status',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only admin user route PATCH /api/admin/users/100000/status route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/admin/users/100000/reset-password',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only admin user route POST /api/admin/users/100000/reset-password route before controller logic runs',
        },
    ],
    AttendanceController: [
        {
            method: 'GET',
            path: '/api/attendance/grid',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-coordinator-accountant attendance route GET /api/attendance/grid route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/attendance',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-coordinator-accountant attendance route POST /api/attendance route before controller logic runs',
        },
        {
            method: 'DELETE',
            path: '/api/attendance/100000/2026-08-18',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-coordinator-accountant attendance route DELETE /api/attendance/100000/2026-08-18 route before controller logic runs',
        },
    ],
    AuthController: [
        {
            method: 'POST',
            path: '/auth/google',
            expected: 400,
            body: {},
            scenario: 'anonymous request fails validation on POST /auth/google when the credential field is missing',
        },
        {
            method: 'POST',
            path: '/auth/forgot-password/request',
            expected: 400,
            body: {},
            scenario: 'anonymous request fails validation on POST /auth/forgot-password/request when email is missing',
        },
        {
            method: 'POST',
            path: '/auth/forgot-password/verify',
            expected: 400,
            body: {},
            scenario: 'anonymous request fails validation on POST /auth/forgot-password/verify when email and code are missing',
        },
        {
            method: 'POST',
            path: '/auth/forgot-password/reset',
            expected: 400,
            body: {},
            scenario: 'anonymous request fails validation on POST /auth/forgot-password/reset when reset payload is incomplete',
        },
        {
            method: 'POST',
            path: '/auth/refresh',
            expected: 401,
            body: {},
            scenario: 'anonymous request is rejected on POST /auth/refresh when no refresh token is supplied',
        },
        {
            method: 'POST',
            path: '/auth/logout',
            expected: 200,
            body: {},
            scenario: 'anonymous request can still call POST /auth/logout and receives the normal logout response',
        },
    ],
    BonusController: [
        {
            method: 'GET',
            path: '/api/bonuses/my',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only bonus route GET /api/bonuses/my route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/bonuses',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant bonus route GET /api/bonuses route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/bonuses/stats',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant bonus route GET /api/bonuses/stats route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/bonuses/staff-lookup',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant bonus route GET /api/bonuses/staff-lookup route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/bonuses/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant bonus route GET /api/bonuses/100000 route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/bonuses',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant bonus route POST /api/bonuses route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/bonuses/tet/preview',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only bonus route GET /api/bonuses/tet/preview route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/bonuses/tet/generate',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only bonus route POST /api/bonuses/tet/generate route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/bonuses/100000/approve',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only bonus route PATCH /api/bonuses/100000/approve route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/bonuses/100000/reject',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only bonus route PATCH /api/bonuses/100000/reject route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/bonuses/100000/pay',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only bonus route PATCH /api/bonuses/100000/pay route before controller logic runs',
        },
    ],
    BonusRuleController: [
        {
            method: 'GET',
            path: '/api/bonus-rules',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant bonus-rule route GET /api/bonus-rules route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/bonus-rules/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant bonus-rule route GET /api/bonus-rules/100000 route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/bonus-rules',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only bonus-rule route POST /api/bonus-rules route before controller logic runs',
        },
        {
            method: 'PUT',
            path: '/api/bonus-rules/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only bonus-rule route PUT /api/bonus-rules/100000 route before controller logic runs',
        },
        {
            method: 'DELETE',
            path: '/api/bonus-rules/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only bonus-rule route DELETE /api/bonus-rules/100000 route before controller logic runs',
        },
    ],
    CompanyController: [
        {
            method: 'POST',
            path: '/api/company/bank-qr',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-admin only POST /api/company/bank-qr route before controller logic runs',
        },
    ],
    CoordinatorController: [
        {
            method: 'GET',
            path: '/api/coordinator/dashboard',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only GET /api/coordinator/dashboard route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/coordinator/partners',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only GET /api/coordinator/partners route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/coordinator/incidents',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only GET /api/coordinator/incidents route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/coordinator/trips/100000/cancel',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only PATCH /api/coordinator/trips/100000/cancel route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/coordinator/trips/100000/reassign',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only PATCH /api/coordinator/trips/100000/reassign route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/coordinator/orders/100000/assign-driver',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only POST /api/coordinator/orders/100000/assign-driver route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/coordinator/trips/100000/resolve-failed',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only POST /api/coordinator/trips/100000/resolve-failed route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/coordinator/receipt-requests',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only GET /api/coordinator/receipt-requests route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/coordinator/receipt-requests/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only GET /api/coordinator/receipt-requests/100000 route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/coordinator/receipt-requests/100000/approve',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only POST /api/coordinator/receipt-requests/100000/approve route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/coordinator/receipt-requests/100000/reject',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only POST /api/coordinator/receipt-requests/100000/reject route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/coordinator/receipt-requests/100000/scan-expenses',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only GET /api/coordinator/receipt-requests/100000/scan-expenses route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/coordinator/expenses/100000/approve',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only PATCH /api/coordinator/expenses/100000/approve route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/coordinator/expenses/100000/reject',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only PATCH /api/coordinator/expenses/100000/reject route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/coordinator/expenses/100000/unapprove',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only PATCH /api/coordinator/expenses/100000/unapprove route before controller logic runs',
        },
    ],
    CustomerController: [
        {
            method: 'GET',
            path: '/api/customers',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager customer route GET /api/customers route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/customers/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager customer route GET /api/customers/100000 route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/customers',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager customer route POST /api/customers route before controller logic runs',
        },
        {
            method: 'PUT',
            path: '/api/customers/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager customer route PUT /api/customers/100000 route before controller logic runs',
        },
        {
            method: 'DELETE',
            path: '/api/customers/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager customer route DELETE /api/customers/100000 route before controller logic runs',
        },
    ],
    DebtController: [
        {
            method: 'PATCH',
            path: '/api/debts/repayments/100000/confirm',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-manager finance-only PATCH /api/debts/repayments/100000/confirm route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/debts/repayments/100000/reject',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-manager finance-only PATCH /api/debts/repayments/100000/reject route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/debts/repayments/100000/void',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-manager finance-only PATCH /api/debts/repayments/100000/void route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/debts/me',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/debts/me route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/debts/100000/payments',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/debts/100000/payments route before controller logic runs',
        },
        {
            method: 'DELETE',
            path: '/api/debts/repayments/100000',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only DELETE /api/debts/repayments/100000 route before controller logic runs',
        },
    ],
    DriverController: [
        {
            method: 'GET',
            path: '/api/drivers/me/assignment-history',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/drivers/me/assignment-history route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/drivers/maintenance',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/drivers/maintenance route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/drivers/maintenance/request',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only POST /api/drivers/maintenance/request route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/drivers/maintenance/100000/bills',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only POST /api/drivers/maintenance/100000/bills route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/drivers/maintenance/100000/cost',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only PATCH /api/drivers/maintenance/100000/cost route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/drivers/maintenance/100000/complete',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only POST /api/drivers/maintenance/100000/complete route before controller logic runs',
        },
    ],
    ExpenseController: [
        {
            method: 'PATCH',
            path: '/api/expenses/100000',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only PATCH /api/expenses/100000 route before controller logic runs',
        },
        {
            method: 'DELETE',
            path: '/api/expenses/100000',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only DELETE /api/expenses/100000 route before controller logic runs',
        },
    ],
    HolidayController: [
        {
            method: 'GET',
            path: '/api/admin/holidays',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route GET /api/admin/holidays route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/admin/holidays',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route POST /api/admin/holidays route before controller logic runs',
        },
        {
            method: 'DELETE',
            path: '/api/admin/holidays/2026-08-18',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route DELETE /api/admin/holidays/2026-08-18 route before controller logic runs',
        },
    ],
    IncidentController: [
        {
            method: 'GET',
            path: '/api/incidents/my/counts',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/incidents/my/counts route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/incidents/my',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/incidents/my route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/incidents/shipment/100000',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/incidents/shipment/100000 route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/incidents/100000/status',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager staff-only PATCH /api/incidents/100000/status route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/incidents/100000/cancel-shipment',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager staff-only POST /api/incidents/100000/cancel-shipment route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/incidents/staff',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager staff-only POST /api/incidents/staff route before controller logic runs',
        },
    ],
    KpiController: [
        {
            method: 'GET',
            path: '/api/kpi/all',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager staff-only GET /api/kpi/all route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/kpi/leaderboard/group/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager staff-only GET /api/kpi/leaderboard/group/100000 route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/kpi/driver/100000/vehicle-group/history',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager staff-only GET /api/kpi/driver/100000/vehicle-group/history route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/kpi/driver/100000/vehicle-group',
            role: 'accountant',
            expected: 403,
            scenario: 'accountant token is rejected from manager-only PATCH /api/kpi/driver/100000/vehicle-group route before controller logic runs',
        },
    ],
    LeaveController: [
        {
            method: 'GET',
            path: '/api/leave/attendance',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/leave/attendance route before controller logic runs',
        },
    ],
    ManagerController: [
        {
            method: 'GET',
            path: '/api/manager/dashboard',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only GET /api/manager/dashboard route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/manager/reports/overview',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only GET /api/manager/reports/overview route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/manager/reports/business',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only GET /api/manager/reports/business route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/manager/reports/periods',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only GET /api/manager/reports/periods route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/manager/reports/periods/preflight',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only GET /api/manager/reports/periods/preflight route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/manager/reports/periods/sign-off',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only POST /api/manager/reports/periods/sign-off route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/manager/trips/100000/cancel',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only PATCH /api/manager/trips/100000/cancel route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/manager/trips/100000/reassign',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only PATCH /api/manager/trips/100000/reassign route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/manager/incidents',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only GET /api/manager/incidents route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/manager/salary-advances',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only GET /api/manager/salary-advances route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/manager/salary-advances/100000/approve',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only PATCH /api/manager/salary-advances/100000/approve route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/manager/salary-advances/100000/reject',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only PATCH /api/manager/salary-advances/100000/reject route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/manager/debt-repayments',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only GET /api/manager/debt-repayments route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/manager/debt-repayments/100000/confirm',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only PATCH /api/manager/debt-repayments/100000/confirm route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/manager/debt-repayments/100000/reject',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only PATCH /api/manager/debt-repayments/100000/reject route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/manager/payrolls',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only GET /api/manager/payrolls route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/manager/payrolls/100000/review',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only PATCH /api/manager/payrolls/100000/review route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/manager/payrolls/100000/revert',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only PATCH /api/manager/payrolls/100000/revert route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/manager/receipt-requests',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only GET /api/manager/receipt-requests route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/manager/partners',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only GET /api/manager/partners route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/manager/partners',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only POST /api/manager/partners route before controller logic runs',
        },
        {
            method: 'PUT',
            path: '/api/manager/partners/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only PUT /api/manager/partners/100000 route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/manager/partners/100000/debts',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only GET /api/manager/partners/100000/debts route before controller logic runs',
        },
    ],
    NotificationController: [
        {
            method: 'PATCH',
            path: '/api/notifications/100000/read',
            expected: 403,
            scenario: 'unauthenticated request is rejected from authenticated notification route PATCH /api/notifications/100000/read route before controller logic runs',
        },
    ],
    OrderController: [
        {
            method: 'GET',
            path: '/api/orders',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager-admin GET /api/orders route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/orders',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager-admin POST /api/orders route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/orders/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager-admin PATCH /api/orders/100000 route before controller logic runs',
        },
        {
            method: 'DELETE',
            path: '/api/orders/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager-admin DELETE /api/orders/100000 route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/orders/import',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager-admin POST /api/orders/import route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/orders/prepaid/pending',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager-admin GET /api/orders/prepaid/pending route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/orders/100000/prepaid/confirm',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager-admin PATCH /api/orders/100000/prepaid/confirm route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/orders/100000/prepaid/reject',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-manager-admin PATCH /api/orders/100000/prepaid/reject route before controller logic runs',
        },
    ],
    PaymentController: [
        {
            method: 'GET',
            path: '/api/trips/100000/payments',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/trips/100000/payments route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/trips/100000/payment-summary',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/trips/100000/payment-summary route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/trips/100000/payments/100000',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only PATCH /api/trips/100000/payments/100000 route before controller logic runs',
        },
    ],
    PayrollController: [
        {
            method: 'GET',
            path: '/api/payroll/estimate',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/payroll/estimate route before controller logic runs',
        },
    ],
    ProfileController: [
        {
            method: 'POST',
            path: '/api/profile/me/email/send-code',
            expected: 403,
            scenario: 'unauthenticated request is rejected from authenticated profile route POST /api/profile/me/email/send-code route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/profile/me/email/verify',
            expected: 403,
            scenario: 'unauthenticated request is rejected from authenticated profile route POST /api/profile/me/email/verify route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/profile/me/avatar',
            expected: 403,
            scenario: 'unauthenticated request is rejected from authenticated profile route POST /api/profile/me/avatar route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/profile/me/device-token',
            expected: 403,
            scenario: 'unauthenticated request is rejected from authenticated profile route POST /api/profile/me/device-token route before controller logic runs',
        },
    ],
    SpendingController: [
        {
            method: 'GET',
            path: '/api/coordinator/expenses',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only GET /api/coordinator/expenses route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/manager/expenses',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only GET /api/manager/expenses route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/manager/vouchers',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only GET /api/manager/vouchers route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/manager/vouchers/100000/approve',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only PATCH /api/manager/vouchers/100000/approve route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/manager/vouchers/100000/reject',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only PATCH /api/manager/vouchers/100000/reject route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/manager/spending-summary',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only GET /api/manager/spending-summary route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/expenses',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/expenses route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/vouchers',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/vouchers route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/accountant/vouchers',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only POST /accountant/vouchers route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/accountant/vouchers/100000/pay',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only PATCH /accountant/vouchers/100000/pay route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/accountant/vouchers/100000/cancel',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only PATCH /accountant/vouchers/100000/cancel route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/reimbursements',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/reimbursements route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/accountant/reimbursements',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only POST /accountant/reimbursements route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/accountant/spending-summary',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from accountant-only GET /accountant/spending-summary route before controller logic runs',
        },
    ],
    TripController: [
        {
            method: 'GET',
            path: '/api/trips/stats',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/trips/stats route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/trips/history',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/trips/history route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/trips/orders/100000',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/trips/orders/100000 route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/trips/pool-shipment/100000',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/trips/pool-shipment/100000 route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/trips/pool/100000',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/trips/pool/100000 route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/trips/100000/release',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only POST /api/trips/100000/release route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/trips/100000/start-transit',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only POST /api/trips/100000/start-transit route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/trips/100000/return-complete',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only POST /api/trips/100000/return-complete route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/trips/100000/complete',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only POST /api/trips/100000/complete route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/trips/pending-receipt',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/trips/pending-receipt route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/trips/receipt-requests',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/trips/receipt-requests route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/trips/receipt-requests/100000',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/trips/receipt-requests/100000 route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/trips/receipt-requests/100000/resubmit',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only POST /api/trips/receipt-requests/100000/resubmit route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/trips/receipt-requests/100000/record-collection',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only POST /api/trips/receipt-requests/100000/record-collection route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/trips/100000/stops/100000/arrive',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only PATCH /api/trips/100000/stops/100000/arrive route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/trips/100000/stops/100000/complete',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only PATCH /api/trips/100000/stops/100000/complete route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/orders/100000/request-receipt',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only POST /api/orders/100000/request-receipt route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/orders/100000/receipt-request',
            role: 'coordinator',
            expected: 403,
            scenario: 'coordinator token is rejected from driver-only GET /api/orders/100000/receipt-request route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/coordinator/trip-pool',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from coordinator-only GET /api/coordinator/trip-pool route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/manager/trip-pool',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-only GET /api/manager/trip-pool route before controller logic runs',
        },
    ],
    VehicleManagementController: [
        {
            method: 'GET',
            path: '/api/admin/vehicle-groups',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route GET /api/admin/vehicle-groups route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/admin/vehicle-groups',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route POST /api/admin/vehicle-groups route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/admin/vehicle-groups/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route GET /api/admin/vehicle-groups/100000 route before controller logic runs',
        },
        {
            method: 'PUT',
            path: '/api/admin/vehicle-groups/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route PUT /api/admin/vehicle-groups/100000 route before controller logic runs',
        },
        {
            method: 'DELETE',
            path: '/api/admin/vehicle-groups/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route DELETE /api/admin/vehicle-groups/100000 route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/admin/vehicle-groups/100000/restore',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route POST /api/admin/vehicle-groups/100000/restore route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/admin/vehicles/driver-options',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route GET /api/admin/vehicles/driver-options route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/admin/vehicles',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route GET /api/admin/vehicles route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/admin/vehicles',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route POST /api/admin/vehicles route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/admin/vehicles/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route GET /api/admin/vehicles/100000 route before controller logic runs',
        },
        {
            method: 'PUT',
            path: '/api/admin/vehicles/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route PUT /api/admin/vehicles/100000 route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/admin/maintenance-requests',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route GET /api/admin/maintenance-requests route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/admin/maintenance-requests/100000/approve',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route POST /api/admin/maintenance-requests/100000/approve route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/admin/maintenance-requests/100000/reject',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route POST /api/admin/maintenance-requests/100000/reject route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/admin/vehicles/100000/send-to-maintenance',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route POST /api/admin/vehicles/100000/send-to-maintenance route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/admin/vehicles/100000/complete-maintenance',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route POST /api/admin/vehicles/100000/complete-maintenance route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/admin/vehicles/100000/verify-maintenance',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route POST /api/admin/vehicles/100000/verify-maintenance route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/admin/vehicles/100000/reject-maintenance',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route POST /api/admin/vehicles/100000/reject-maintenance route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/admin/vehicles/100000/mark-broken',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route POST /api/admin/vehicles/100000/mark-broken route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/admin/vehicles/100000/restore',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route POST /api/admin/vehicles/100000/restore route before controller logic runs',
        },
        {
            method: 'POST',
            path: '/api/admin/vehicles/100000/retire',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route POST /api/admin/vehicles/100000/retire route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/admin/vehicles/100000/status',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route PATCH /api/admin/vehicles/100000/status route before controller logic runs',
        },
        {
            method: 'PATCH',
            path: '/api/admin/vehicles/100000/driver-assignment',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route PATCH /api/admin/vehicles/100000/driver-assignment route before controller logic runs',
        },
        {
            method: 'GET',
            path: '/api/admin/vehicles/100000/assignment-history',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route GET /api/admin/vehicles/100000/assignment-history route before controller logic runs',
        },
        {
            method: 'DELETE',
            path: '/api/admin/vehicles/100000',
            role: 'driver',
            expected: 403,
            scenario: 'driver token is rejected from manager-accountant protected admin vehicle route DELETE /api/admin/vehicles/100000 route before controller logic runs',
        },
    ],
};
