-- Phase 3 — Chốt kỳ báo cáo kinh doanh (immutable snapshot + ký duyệt).
-- Chạy script này trên DB đang có sẵn; DB tạo mới từ "DB script.sql" đã bao gồm thay đổi này.
-- An toàn khi chạy lại nhiều lần.
--
-- Mỗi (năm, tháng) chốt được 1 lần → lưu nguyên bản báo cáo tại thời điểm chốt vào
-- cột snapshot (JSONB) để số liệu KHÔNG đổi khi có giao dịch phát sinh về sau.
-- Các chỉ số P&L then chốt được tách cột riêng để liệt kê nhanh không cần đọc JSON.
--   status: closed     = đã chốt, số đóng băng
--           signed_off = Manager đã ký duyệt (khoá cứng, không mở lại được)

BEGIN;

CREATE TABLE IF NOT EXISTS business_report_periods (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_year     SMALLINT NOT NULL,
    period_month    SMALLINT NOT NULL CHECK (period_month BETWEEN 1 AND 12),
    status          TEXT NOT NULL DEFAULT 'closed'
                        CHECK (status IN ('closed','signed_off')),
    snapshot        JSONB NOT NULL,

    revenue         NUMERIC(14,2) NOT NULL DEFAULT 0,
    operating_cost  NUMERIC(14,2) NOT NULL DEFAULT 0,
    payroll_cost    NUMERIC(14,2) NOT NULL DEFAULT 0,
    gross_profit    NUMERIC(14,2) NOT NULL DEFAULT 0,
    margin_pct      NUMERIC(6,2)  NOT NULL DEFAULT 0,

    note            TEXT,
    closed_by       INT NOT NULL REFERENCES profiles(id),
    closed_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    signed_off_by   INT REFERENCES profiles(id),
    signed_off_at   TIMESTAMPTZ,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (period_year, period_month)
);

CREATE INDEX IF NOT EXISTS idx_business_report_periods_ym
    ON business_report_periods(period_year, period_month);

COMMIT;
