

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE roles (
    id   INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    name TEXT UNIQUE NOT NULL  -- manager | coordinator | accountant | driver
);

INSERT INTO roles (name) VALUES
    ('manager'), ('coordinator'), ('accountant'), ('driver')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE accounts (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    email           TEXT UNIQUE NOT NULL,
    password_hash   TEXT NOT NULL,
    role_id         INT NOT NULL REFERENCES roles(id),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE profiles (
    id          INT PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
    full_name   TEXT NOT NULL,
    phone       TEXT UNIQUE,
    role_id     INT NOT NULL REFERENCES roles(id),
    avatar_url  TEXT,
    dob         DATE,
    gender      TEXT CHECK (gender IN ('male','female','other')),
    address     TEXT,
    city        TEXT,
    country     TEXT NOT NULL DEFAULT 'VN',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE vehicle_groups (
    id                  INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    name                TEXT NOT NULL UNIQUE,           -- "5m2" | "1T25" | "2T5" (spec §26)
    description         TEXT,
    max_load_weight_kg  NUMERIC(10,2),
    price_per_km        NUMERIC(12,2) NOT NULL,
    depreciation_per_km NUMERIC(10,2) NOT NULL DEFAULT 0,
    upgrade_allowed     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE vehicles (
    id                  INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    plate_number        TEXT UNIQUE NOT NULL,
    vehicle_group_id    INT NOT NULL REFERENCES vehicle_groups(id),
    brand               TEXT,
    model               TEXT,
    load_capacity_kg    NUMERIC(10,2),
    manufacture_year    SMALLINT,
    purchase_date       DATE,
    assigned_driver_id  INT REFERENCES profiles(id),   -- 1-1, enforced via drivers.vehicle_id UNIQUE
    status              TEXT NOT NULL DEFAULT 'active'
                            CHECK (status IN ('active','retired','maintenance','broken')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE drivers (
    profile_id              INT PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
    vehicle_id              INT UNIQUE REFERENCES vehicles(id),   -- UNIQUE → 1-1 (spec §9)
    license_number          TEXT NOT NULL,
    license_expiry_date     DATE,
    hire_date               DATE NOT NULL,    -- <12 months → 8M base; >=12 → 9M (spec §28)
    emergency_contact_name  TEXT,
    emergency_contact_phone TEXT,
    revenue_share_percent   NUMERIC(5,2) NOT NULL DEFAULT 15.00,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);



CREATE TABLE customers (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    customer_type   TEXT NOT NULL CHECK (customer_type IN ('individual','business')),
    full_name       TEXT,
    company_name    TEXT,
    contact_person  TEXT,
    phone           TEXT NOT NULL,
    email           TEXT,
    address         TEXT,
    tax_code        TEXT,
    current_debt    NUMERIC(12,2) NOT NULL DEFAULT 0,
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE partners (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    company_name    TEXT NOT NULL,
    contact_person  TEXT,
    phone           TEXT,
    email           TEXT,
    address         TEXT,
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE orders (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    customer_id     INT REFERENCES customers(id),
    created_by      INT NOT NULL REFERENCES profiles(id),
    updated_by      INT REFERENCES profiles(id),

    cargo_name          TEXT,
    cargo_weight_kg     NUMERIC(10,2),
    payment_type        TEXT CHECK (payment_type IN ('cash','bank_transfer','client_credit')),

    total_estimated_price   NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_actual_price      NUMERIC(12,2) NOT NULL DEFAULT 0,
    derived_status      TEXT NOT NULL DEFAULT 'open'
                            CHECK (derived_status IN ('open','completed','cancelled','partial')),
    is_confidential     BOOLEAN NOT NULL DEFAULT FALSE,
    notes               TEXT,
    import_batch_id     TEXT,    
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- SECTION 5 — ORDER SHIPMENTS  (= "Trip" in spec)
-- Primary operational unit. Coordinator and Driver work here. (spec §5, §30)
-- =============================================================================

CREATE TABLE order_shipments (
    id                  INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    order_id            INT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    shipment_index      SMALLINT NOT NULL,       -- 1-based within order
    trip_code           TEXT UNIQUE,             -- human-readable: "CH-2024-00123"
    vehicle_group_id    INT NOT NULL REFERENCES vehicle_groups(id),
    owner_driver_id     INT REFERENCES profiles(id),
    vehicle_id          INT REFERENCES vehicles(id),
    estimated_price     NUMERIC(12,2),
    estimated_distance_km NUMERIC(10,2),
    actual_distance_km NUMERIC(10,2),
    actual_price        NUMERIC(12,2),
    cargo_name          TEXT,
    cargo_weight_kg     NUMERIC(10,2),
    status              TEXT NOT NULL DEFAULT 'available'
                            CHECK (status IN (
                                'available',  
                                'claimed', 
                                'picking',   
                                'loaded',  
                                'transit', 
                                'arrived',   
                                'completed',   
                                'failed',   
                                'returning',  
                                'cancelled'  
                            )),

    version             INT NOT NULL DEFAULT 0,

    notes               TEXT,
    cancel_reason       TEXT,

    claimed_at          TIMESTAMPTZ,
    picking_at          TIMESTAMPTZ,
    loaded_at           TIMESTAMPTZ,
    transit_at          TIMESTAMPTZ,
    arrived_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    failed_at           TIMESTAMPTZ,
    returning_at        TIMESTAMPTZ,   -- ← added: trả hàng về
    cancelled_at        TIMESTAMPTZ,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (order_id, shipment_index)
);



CREATE TABLE trip_stops (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    shipment_id     INT NOT NULL REFERENCES order_shipments(id) ON DELETE CASCADE,
    stop_index      SMALLINT NOT NULL,   -- 1-based sequence order
    stop_type       TEXT NOT NULL CHECK (stop_type IN ('pickup','delivery')),
    address         TEXT NOT NULL,
    contact_name    TEXT,
    contact_phone   TEXT,
    notes           TEXT,
    arrived_at      TIMESTAMPTZ,         -- driver confirmed arrival
    completed_at    TIMESTAMPTZ,         -- driver completed this stop
    proof_url       TEXT,                -- optional per-stop photo evidence
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (shipment_id, stop_index)
);



CREATE TABLE trip_runs (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    shipment_id     INT NOT NULL REFERENCES order_shipments(id) ON DELETE CASCADE,
    run_index       SMALLINT NOT NULL,   -- 1-based: Run 1, Run 2, ...
    driver_id       INT REFERENCES profiles(id),
    vehicle_id      INT REFERENCES vehicles(id),
    status          TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','in_progress','completed','failed')),
    started_at      TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ,
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (shipment_id, run_index)
);


CREATE TABLE shipment_assignments (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    shipment_id     INT NOT NULL REFERENCES order_shipments(id) ON DELETE CASCADE,
    driver_id       INT NOT NULL REFERENCES profiles(id),
    vehicle_id      INT NOT NULL REFERENCES vehicles(id),
    assignment_type TEXT NOT NULL CHECK (assignment_type IN ('coordinator_assign','self_claim')),
    assigned_by     INT REFERENCES profiles(id),   -- NULL when self_claim
    assigned_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    accepted_at     TIMESTAMPTZ,
    completed_at    TIMESTAMPTZ
);


CREATE TABLE pass_through_costs (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    shipment_id     INT NOT NULL REFERENCES order_shipments(id) ON DELETE CASCADE,
    cost_type       TEXT NOT NULL CHECK (cost_type IN ('bot','ferry','port_fee','road_fee','other')),
    description     TEXT,
    amount          NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    paid_by         TEXT NOT NULL CHECK (paid_by IN ('driver','company')),
    collected_from  TEXT NOT NULL CHECK (collected_from IN ('customer','driver')),
    receipt_url     TEXT,
    recorded_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      INT NOT NULL REFERENCES profiles(id)
    -- !! NEVER include this table in revenue/KPI/bonus queries !!
);


CREATE TABLE shipment_payments (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    shipment_id     INT NOT NULL REFERENCES order_shipments(id) ON DELETE CASCADE,
    payment_type    TEXT NOT NULL CHECK (payment_type IN ('cash_collected','bank_transfer','client_credit')),
    amount          NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    collected_by    INT REFERENCES profiles(id),   -- driver who collected (TH2)
    collected_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Receipt images per payment — cash requires ≥1 (spec §15)
CREATE TABLE payment_receipts (
    id          INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    payment_id  INT NOT NULL REFERENCES shipment_payments(id) ON DELETE CASCADE,
    file_url    TEXT NOT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);



CREATE TABLE delivery_proofs (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    shipment_id     INT NOT NULL REFERENCES order_shipments(id) ON DELETE CASCADE,
    captured_by     INT NOT NULL REFERENCES profiles(id),
    file_url        TEXT NOT NULL,
    is_realtime     BOOLEAN NOT NULL DEFAULT TRUE,
    captured_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE expenses (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    shipment_id     INT REFERENCES order_shipments(id),   -- nullable (vehicle-level costs)
    vehicle_id      INT REFERENCES vehicles(id),
    created_by      INT NOT NULL REFERENCES profiles(id),
    updated_by      INT REFERENCES profiles(id),
    expense_type    TEXT NOT NULL
                        CHECK (expense_type IN (
                            'fuel','toll','parking','repair',
                            'maintenance','depreciation','other'
                        )),
    amount          NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    description     TEXT,
    expense_date    DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE expense_attachments (
    id          INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    expense_id  INT NOT NULL REFERENCES expenses(id) ON DELETE CASCADE,
    file_url    TEXT NOT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE maintenance_records (
    id                  INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    vehicle_id          INT NOT NULL REFERENCES vehicles(id),
    expense_id          INT REFERENCES expenses(id),
    maintenance_type    TEXT NOT NULL
                            CHECK (maintenance_type IN ('scheduled','repair','inspection','emergency')),
    description         TEXT,
    cost                NUMERIC(12,2),
    maintenance_date    DATE NOT NULL,
    next_due_date       DATE,
    performed_by        TEXT,
    status              TEXT NOT NULL DEFAULT 'open'
                            CHECK (status IN ('open','completed')),
    started_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at        TIMESTAMPTZ,
    completion_note     TEXT,
    created_by          INT REFERENCES profiles(id),
    completed_by        INT REFERENCES profiles(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE vehicle_status_history (
    id                  INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    vehicle_id          INT NOT NULL REFERENCES vehicles(id),
    action_type         TEXT NOT NULL
                            CHECK (action_type IN (
                                'send_to_maintenance',
                                'complete_maintenance',
                                'mark_broken',
                                'restore_vehicle',
                                'retire_vehicle'
                            )),
    from_status         TEXT NOT NULL
                            CHECK (from_status IN ('active','maintenance','broken','retired')),
    to_status           TEXT NOT NULL
                            CHECK (to_status IN ('active','maintenance','broken','retired')),
    reference_type      TEXT,
    reference_id        INT,
    note                TEXT,
    metadata            JSONB,
    created_by          INT REFERENCES profiles(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE debts (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    debt_type       TEXT NOT NULL CHECK (debt_type IN ('customer','partner','driver')),
    customer_id     INT REFERENCES customers(id),
    partner_id      INT REFERENCES partners(id),
    driver_id       INT REFERENCES profiles(id),
    order_id        INT REFERENCES orders(id),
    shipment_id     INT REFERENCES order_shipments(id),   -- finer traceability
    total_amount    NUMERIC(12,2) NOT NULL CHECK (total_amount > 0),
    paid_amount     NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
    due_date        DATE,
    status          TEXT NOT NULL DEFAULT 'unpaid'
                        CHECK (status IN ('unpaid','partial','paid','overdue')),
    notes           TEXT,
    updated_by      INT REFERENCES profiles(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT debt_no_overpay CHECK (paid_amount <= total_amount)
);

-- Driver gửi yêu cầu nộp tiền → kế toán xác nhận → debt giảm tương ứng
CREATE TABLE debt_payments (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    debt_id         INT NOT NULL REFERENCES debts(id) ON DELETE CASCADE,
    amount          NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    payment_method  TEXT CHECK (payment_method IN ('cash','bank_transfer','offset')),
    status          TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','confirmed','rejected')),
    receipt_url     TEXT,           -- ảnh chứng từ driver upload
    reject_reason   TEXT,           -- lý do kế toán từ chối
    paid_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    confirmed_at    TIMESTAMPTZ,
    confirmed_by    INT REFERENCES profiles(id),
    created_by      INT NOT NULL REFERENCES profiles(id),
    notes           TEXT
);



CREATE TABLE invoices (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    invoice_number  TEXT UNIQUE NOT NULL,   -- "INV-2024-00001"
    customer_id     INT NOT NULL REFERENCES customers(id),
    order_id        INT REFERENCES orders(id),    -- NULL if spans multiple orders
    created_by      INT NOT NULL REFERENCES profiles(id),
    invoice_date    DATE NOT NULL DEFAULT CURRENT_DATE,
    due_date        DATE,
    tax_rate        NUMERIC(5,2) NOT NULL DEFAULT 10.00,  -- VAT %
    subtotal        NUMERIC(12,2) NOT NULL DEFAULT 0,
    tax_amount      NUMERIC(12,2) GENERATED ALWAYS AS (subtotal * tax_rate / 100) STORED,
    total_amount    NUMERIC(12,2) GENERATED ALWAYS AS (subtotal + subtotal * tax_rate / 100) STORED,
    status          TEXT NOT NULL DEFAULT 'draft'
                        CHECK (status IN ('draft','sent','partial','paid','overdue','cancelled')),
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Which shipments are on this invoice (1 or many — spec §29)
CREATE TABLE invoice_shipments (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    invoice_id      INT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    shipment_id     INT NOT NULL REFERENCES order_shipments(id),
    line_amount     NUMERIC(12,2) NOT NULL,  -- actual_price snapshot at invoice time
    UNIQUE (invoice_id, shipment_id)
);



CREATE TABLE kpi_records (
    id                      INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    driver_id               INT NOT NULL REFERENCES profiles(id),
    vehicle_group_id        INT NOT NULL REFERENCES vehicle_groups(id),
    month                   SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12),
    year                    SMALLINT NOT NULL CHECK (year >= 2020),
    completed_shipments     INT NOT NULL DEFAULT 0,
    total_revenue           NUMERIC(12,2) NOT NULL DEFAULT 0,  -- SUM(actual_price) only
    late_deliveries         INT NOT NULL DEFAULT 0,
    incident_count          INT NOT NULL DEFAULT 0,            -- all severities
    major_incident_count    INT NOT NULL DEFAULT 0,            -- severity = 'high'
    critical_incident_count INT NOT NULL DEFAULT 0,            -- severity = 'critical'
    on_time_rate            NUMERIC(5,2) GENERATED ALWAYS AS (
                                CASE WHEN completed_shipments = 0 THEN 0
                                ELSE ROUND(
                                    (completed_shipments - late_deliveries)::NUMERIC
                                    / completed_shipments * 100, 2)
                                END
                            ) STORED,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (driver_id, month, year)
);


CREATE TABLE bonus_rules (
    id                  INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    vehicle_group_id    INT REFERENCES vehicle_groups(id),  -- NULL = all groups
    title               TEXT NOT NULL,
    bonus_type          TEXT NOT NULL
                            CHECK (bonus_type IN (
                                'kpi','top_revenue','top_trips',
                                'zero_incident','overtime','holiday','custom'
                            )),
    reward_amount       NUMERIC(12,2),
    reward_multiplier   NUMERIC(5,2),
    conditions_json     JSONB,   -- {"min_trips": 20, "rank": 1}
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE bonus_records (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    driver_id       INT NOT NULL REFERENCES profiles(id),
    bonus_rule_id   INT REFERENCES bonus_rules(id),
    kpi_record_id   INT REFERENCES kpi_records(id),
    amount          NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    awarded_month   SMALLINT NOT NULL CHECK (awarded_month BETWEEN 1 AND 12),
    awarded_year    SMALLINT NOT NULL,
    notes           TEXT,
    created_by      INT NOT NULL REFERENCES profiles(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE payrolls (
    id                      INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    driver_id               INT NOT NULL REFERENCES profiles(id),
    payroll_month           SMALLINT NOT NULL CHECK (payroll_month BETWEEN 1 AND 12),
    payroll_year            SMALLINT NOT NULL,

    base_salary             NUMERIC(12,2) NOT NULL,   -- 8M (<12 months) or 9M (≥12)
    months_of_service       INT NOT NULL,

    total_revenue           NUMERIC(12,2) NOT NULL DEFAULT 0,
    revenue_share_pct       NUMERIC(5,2) NOT NULL DEFAULT 15.00,
    revenue_bonus           NUMERIC(12,2) NOT NULL DEFAULT 0,

    kpi_bonus               NUMERIC(12,2) NOT NULL DEFAULT 0,
    top_driver_bonus        NUMERIC(12,2) NOT NULL DEFAULT 0,
    overtime_bonus          NUMERIC(12,2) NOT NULL DEFAULT 0,
    holiday_bonus           NUMERIC(12,2) NOT NULL DEFAULT 0,
    other_bonus             NUMERIC(12,2) NOT NULL DEFAULT 0,

    insurance_employee      NUMERIC(12,2) NOT NULL DEFAULT 0,
    insurance_company       NUMERIC(12,2) NOT NULL DEFAULT 0,  -- cost center only
    driver_debt_deduction   NUMERIC(12,2) NOT NULL DEFAULT 0,  -- spec §21
    advance_deduction       NUMERIC(12,2) NOT NULL DEFAULT 0,
    absence_penalty         NUMERIC(12,2) NOT NULL DEFAULT 0,
    other_deduction         NUMERIC(12,2) NOT NULL DEFAULT 0,

    gross_salary            NUMERIC(12,2) GENERATED ALWAYS AS (
                                base_salary + revenue_bonus
                                + kpi_bonus + top_driver_bonus
                                + overtime_bonus + holiday_bonus + other_bonus
                            ) STORED,

    -- spec §21: Net Salary = Gross − Driver Debt − deductions
    net_salary              NUMERIC(12,2) GENERATED ALWAYS AS (
                                base_salary + revenue_bonus
                                + kpi_bonus + top_driver_bonus
                                + overtime_bonus + holiday_bonus + other_bonus
                                - insurance_employee
                                - driver_debt_deduction
                                - advance_deduction
                                - absence_penalty
                                - other_deduction
                            ) STORED,

    status                  TEXT NOT NULL DEFAULT 'pending'
                                CHECK (status IN ('pending','reviewed','approved','paid')),
    reviewed_by             INT REFERENCES profiles(id),
    reviewed_at             TIMESTAMPTZ,
    approved_by             INT REFERENCES profiles(id),
    approved_at             TIMESTAMPTZ,
    paid_by                 INT REFERENCES profiles(id),
    paid_at                 TIMESTAMPTZ,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (driver_id, payroll_month, payroll_year)
);


CREATE TABLE salary_advances (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    driver_id       INT NOT NULL REFERENCES profiles(id),
    amount          NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    reason          TEXT,
    request_month   SMALLINT NOT NULL CHECK (request_month BETWEEN 1 AND 12),
    request_year    SMALLINT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','approved','rejected','paid')),
    reviewed_by     INT REFERENCES profiles(id),
    reviewed_at     TIMESTAMPTZ,
    approved_by     INT REFERENCES profiles(id),
    approved_at     TIMESTAMPTZ,
    paid_by         INT REFERENCES profiles(id),
    paid_at         TIMESTAMPTZ,
    reject_reason   TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- Driver tự đăng ký nghỉ — auto-approved.
-- paid: hưởng nguyên lương (nghỉ lễ quốc gia, việc riêng có lương)
-- unpaid: không lương → trừ vào công tháng đó
CREATE TABLE leave_requests (
    id          INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    driver_id   INT NOT NULL REFERENCES profiles(id),
    leave_date  DATE NOT NULL,
    leave_type  TEXT NOT NULL DEFAULT 'unpaid'
                    CHECK (leave_type IN ('paid', 'unpaid')),
    reason      TEXT,
    status      TEXT NOT NULL DEFAULT 'approved'
                    CHECK (status IN ('approved', 'rejected')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (driver_id, leave_date)
);


CREATE TABLE incidents (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    shipment_id     INT REFERENCES order_shipments(id) ON DELETE CASCADE,
    vehicle_id      INT REFERENCES vehicles(id),
    reported_by     INT NOT NULL REFERENCES profiles(id),
    incident_type   TEXT NOT NULL
                        CHECK (incident_type IN (
                            'vehicle_breakdown',
                            'cargo_damage',
                            'road_incident',
                            'customer_refusal',   -- spec §23
                            'traffic_jam',        -- spec §23
                            'other'
                        )),
    severity_level  TEXT NOT NULL DEFAULT 'medium'
                        CHECK (severity_level IN ('low','medium','high','critical')),
    description     TEXT NOT NULL,
    location        TEXT,
    estimated_loss  NUMERIC(12,2) DEFAULT 0,
    status          TEXT NOT NULL DEFAULT 'open'
                        CHECK (status IN ('open','investigating','resolved','closed')),

    resolved_by             INT REFERENCES profiles(id),
    resolution_note         TEXT,
    replacement_vehicle_id  INT REFERENCES vehicles(id),
    replacement_driver_id   INT REFERENCES profiles(id),

    occurred_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE incident_evidences (
    id          INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    incident_id INT NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,
    file_url    TEXT NOT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);



CREATE TABLE notifications (
    id          INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    user_id     INT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    title       TEXT NOT NULL,
    body        TEXT,
    type        TEXT,   
    entity_type TEXT,
    entity_id   INT,
    is_read     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);



CREATE TABLE activity_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- BIGINT: high volume
    user_id     INT REFERENCES profiles(id),
    action      TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id   INT,
    old_data    JSONB,
    new_data    JSONB,
    ip_address  INET,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE shipment_vehicle_upgrades (
    id                      INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    shipment_id             INT NOT NULL REFERENCES order_shipments(id) ON DELETE CASCADE,
    requested_group_id      INT NOT NULL REFERENCES vehicle_groups(id),
    actual_group_id         INT NOT NULL REFERENCES vehicle_groups(id),
    driver_id               INT NOT NULL REFERENCES profiles(id),
    vehicle_id              INT NOT NULL REFERENCES vehicles(id),
    approved_by             INT NOT NULL REFERENCES profiles(id), 
    reason                  TEXT,       
    price_adjustment        NUMERIC(12,2) DEFAULT 0,  
    upgraded_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE UNIQUE INDEX uq_driver_one_active_trip
    ON order_shipments (owner_driver_id)
    WHERE owner_driver_id IS NOT NULL 
      AND status IN ('claimed','picking','loaded','transit','arrived','returning');


CREATE TABLE shipment_assignment_history (
    id                  INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    shipment_id         INT NOT NULL REFERENCES order_shipments(id) ON DELETE CASCADE,

    -- Driver/vehicle bị thay
    from_driver_id      INT REFERENCES profiles(id),   -- NULL nếu là lần assign đầu tiên
    from_vehicle_id     INT REFERENCES vehicles(id),

    -- Driver/vehicle mới
    to_driver_id        INT NOT NULL REFERENCES profiles(id),
    to_vehicle_id       INT NOT NULL REFERENCES vehicles(id),

    -- Ai thực hiện thay đổi
    changed_by          INT NOT NULL REFERENCES profiles(id),
    change_reason       TEXT NOT NULL
                            CHECK (change_reason IN (
                                'initial_assign',     -- lần đầu assign
                                'self_claim',         -- driver tự nhận từ pool
                                'incident_reassign',  -- xe/driver hỏng → thay 
                                'coordinator_swap',   -- coordinator chủ động điều chỉnh
                                'driver_request',     -- driver xin đổi
                                'other'
                            )),
    incident_id         INT REFERENCES incidents(id),  -- link nếu do incident
    notes               TEXT,
    changed_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE INDEX idx_svupgrades_shipment_id ON shipment_vehicle_upgrades(shipment_id);
CREATE INDEX idx_svupgrades_driver_id   ON shipment_vehicle_upgrades(driver_id);

CREATE INDEX idx_assign_hist_shipment   ON shipment_assignment_history(shipment_id);
CREATE INDEX idx_assign_hist_from_drv   ON shipment_assignment_history(from_driver_id);
CREATE INDEX idx_assign_hist_to_drv     ON shipment_assignment_history(to_driver_id);
CREATE INDEX idx_assign_hist_incident   ON shipment_assignment_history(incident_id);


CREATE INDEX idx_accounts_email           ON accounts(email);
CREATE INDEX idx_profiles_role_id         ON profiles(role_id);

CREATE INDEX idx_vehicles_group_id        ON vehicles(vehicle_group_id);
CREATE INDEX idx_vehicles_status          ON vehicles(status);

CREATE INDEX idx_orders_customer_id       ON orders(customer_id);
CREATE INDEX idx_orders_derived_status    ON orders(derived_status);
CREATE INDEX idx_orders_created_by        ON orders(created_by);
CREATE INDEX idx_orders_created_at        ON orders(created_at DESC);

CREATE INDEX idx_shipments_order_id           ON order_shipments(order_id);
CREATE INDEX idx_shipments_status             ON order_shipments(status);
CREATE INDEX idx_shipments_owner_driver_id    ON order_shipments(owner_driver_id);
CREATE INDEX idx_shipments_vehicle_group_id   ON order_shipments(vehicle_group_id);
CREATE INDEX idx_shipments_pool               ON order_shipments(vehicle_group_id, status)
    WHERE status = 'available';

CREATE INDEX idx_trip_stops_shipment_id   ON trip_stops(shipment_id);
CREATE INDEX idx_trip_runs_shipment_id    ON trip_runs(shipment_id);
CREATE INDEX idx_trip_runs_driver_id      ON trip_runs(driver_id);

CREATE INDEX idx_assignments_shipment_id  ON shipment_assignments(shipment_id);
CREATE INDEX idx_assignments_driver_id    ON shipment_assignments(driver_id);

CREATE INDEX idx_ptc_shipment_id          ON pass_through_costs(shipment_id);

CREATE INDEX idx_spayments_shipment_id    ON shipment_payments(shipment_id);
CREATE INDEX idx_dproofs_shipment_id      ON delivery_proofs(shipment_id);

CREATE INDEX idx_expenses_shipment_id     ON expenses(shipment_id);
CREATE INDEX idx_expenses_vehicle_id      ON expenses(vehicle_id);
CREATE INDEX idx_expenses_created_by      ON expenses(created_by);

CREATE INDEX idx_debts_status             ON debts(status);
CREATE INDEX idx_debts_customer_id        ON debts(customer_id);
CREATE INDEX idx_debts_driver_id          ON debts(driver_id);
CREATE INDEX idx_debts_shipment_id        ON debts(shipment_id);

CREATE INDEX idx_invoices_customer_id     ON invoices(customer_id);
CREATE INDEX idx_invoices_order_id        ON invoices(order_id);
CREATE INDEX idx_invoices_status          ON invoices(status);
CREATE INDEX idx_inv_shipments_invoice    ON invoice_shipments(invoice_id);
CREATE INDEX idx_inv_shipments_shipment   ON invoice_shipments(shipment_id);

CREATE INDEX idx_kpi_driver_month_year    ON kpi_records(driver_id, year, month);
CREATE INDEX idx_kpi_group_month_year     ON kpi_records(vehicle_group_id, year, month);

CREATE INDEX idx_bonus_records_driver_id  ON bonus_records(driver_id);

CREATE INDEX idx_payrolls_driver_id       ON payrolls(driver_id);
CREATE INDEX idx_payrolls_status          ON payrolls(status);
CREATE INDEX idx_payrolls_month_year      ON payrolls(payroll_year, payroll_month);

CREATE INDEX idx_advances_driver_id       ON salary_advances(driver_id);
CREATE INDEX idx_advances_status          ON salary_advances(status);

CREATE INDEX idx_incidents_shipment_id    ON incidents(shipment_id);
CREATE INDEX idx_incidents_vehicle_id     ON incidents(vehicle_id);
CREATE INDEX idx_incidents_status         ON incidents(status);

CREATE INDEX idx_notifications_user_id    ON notifications(user_id);
CREATE INDEX idx_notifications_unread     ON notifications(user_id) WHERE is_read = FALSE;

CREATE INDEX idx_logs_user_id             ON activity_logs(user_id);
CREATE INDEX idx_logs_entity              ON activity_logs(entity_type, entity_id);
CREATE INDEX idx_logs_created_at          ON activity_logs(created_at DESC);

CREATE INDEX idx_maintenance_vehicle_id   ON maintenance_records(vehicle_id);
CREATE INDEX idx_maintenance_vehicle_open ON maintenance_records(vehicle_id, status);
CREATE INDEX idx_vehicle_status_hist_vh   ON vehicle_status_history(vehicle_id, created_at DESC);

CREATE VIEW v_leaderboard AS
SELECT
    k.vehicle_group_id,
    vg.name                     AS vehicle_group_name,
    k.year,
    k.month,
    k.driver_id,
    p.full_name                 AS driver_name,
    k.completed_shipments,
    k.total_revenue,
    k.on_time_rate,
    k.incident_count,
    RANK() OVER (
        PARTITION BY k.vehicle_group_id, k.year, k.month
        ORDER BY k.total_revenue DESC
    )                           AS revenue_rank,
    RANK() OVER (
        PARTITION BY k.vehicle_group_id, k.year, k.month
        ORDER BY k.completed_shipments DESC
    )                           AS trips_rank
FROM kpi_records k
JOIN profiles p       ON p.id  = k.driver_id
JOIN vehicle_groups vg ON vg.id = k.vehicle_group_id;

CREATE VIEW v_trip_pool AS
SELECT
    os.id               AS shipment_id,
    os.trip_code,
    os.order_id,
    os.vehicle_group_id,
    vg.name             AS vehicle_group_name,
    os.estimated_price,
    os.cargo_name,
    os.cargo_weight_kg,
    os.status,
    os.version,
    (SELECT address FROM trip_stops
     WHERE shipment_id = os.id AND stop_type = 'pickup'
     ORDER BY stop_index LIMIT 1)  AS first_pickup,
    (SELECT address FROM trip_stops
     WHERE shipment_id = os.id AND stop_type = 'delivery'
     ORDER BY stop_index DESC LIMIT 1) AS last_delivery,
    os.created_at
FROM order_shipments os
JOIN vehicle_groups vg ON vg.id = os.vehicle_group_id
WHERE os.status = 'available';

CREATE VIEW v_driver_debt_summary AS
SELECT
    d.driver_id,
    p.full_name                             AS driver_name,
    SUM(d.total_amount - d.paid_amount)     AS remaining_debt,
    COUNT(*) FILTER (WHERE d.status <> 'paid') AS open_debt_count
FROM debts d
JOIN profiles p ON p.id = d.driver_id
WHERE d.debt_type = 'driver'
  AND d.status IN ('unpaid','partial','overdue')
GROUP BY d.driver_id, p.full_name;

CREATE VIEW v_customer_debt_summary AS
SELECT
    c.id                                    AS customer_id,
    COALESCE(c.company_name, c.full_name)   AS customer_name,
    SUM(d.total_amount - d.paid_amount)     AS remaining_debt,
    COUNT(*) FILTER (WHERE d.status = 'overdue') AS overdue_count
FROM debts d
JOIN customers c ON c.id = d.customer_id
WHERE d.debt_type = 'customer'
  AND d.status IN ('unpaid','partial','overdue')
GROUP BY c.id, c.company_name, c.full_name;
