

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =============================================================================
-- SECTION 1 — AUTH & USER MANAGEMENT
-- =============================================================================

CREATE TABLE accounts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           TEXT UNIQUE NOT NULL,
    password_hash   TEXT NOT NULL,
    is_verified     BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Roles are fixed; seeded below
CREATE TABLE roles (
    id   SMALLINT PRIMARY KEY,
    name TEXT UNIQUE NOT NULL  -- manager | coordinator | accountant | driver
);

INSERT INTO roles (id, name) VALUES
    (1, 'manager'),
    (2, 'coordinator'),
    (3, 'accountant'),
    (4, 'driver');

CREATE TABLE profiles (
    id          BIGINT PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
    full_name   TEXT NOT NULL,
    phone       TEXT UNIQUE,
    role_id     SMALLINT NOT NULL REFERENCES roles(id),
    avatar_url  TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- SECTION 2 — VEHICLE & DRIVER
-- =============================================================================

CREATE TABLE vehicle_groups (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                TEXT NOT NULL UNIQUE,           -- e.g. "Xe tải 1T", "Xe tải 2T"
    description         TEXT,
    max_load_weight_kg  NUMERIC(10,2),
    price_per_km        NUMERIC(12,2) NOT NULL,
    depreciation_per_km NUMERIC(10,2) NOT NULL DEFAULT 0,
    upgrade_allowed     BOOLEAN NOT NULL DEFAULT FALSE, -- allow driver to claim higher-group trip
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE vehicles (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number        TEXT UNIQUE NOT NULL,
    vehicle_group_id    BIGINT NOT NULL REFERENCES vehicle_groups(id),
    brand               TEXT,
    model               TEXT,
    load_capacity_kg    NUMERIC(10,2),
    manufacture_year    SMALLINT,
    purchase_date       DATE,
    -- 1-1 with driver; set via trigger or application logic
    assigned_driver_id  BIGINT REFERENCES profiles(id),
    status              TEXT NOT NULL DEFAULT 'available'
                            CHECK (status IN ('available','in_delivery','maintenance','inactive')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE drivers (
    -- profile_id IS the PK; driver = profile with role_id=4
    profile_id              BIGINT PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
    vehicle_id              BIGINT UNIQUE REFERENCES vehicles(id),    -- 1-1 enforced by UNIQUE
    license_number          TEXT NOT NULL,
    license_expiry_date     DATE,
    hire_date               DATE NOT NULL,    -- used for base salary tier (<12 / >=12 months)
    emergency_contact_name  TEXT,
    emergency_contact_phone TEXT,
    revenue_share_percent   NUMERIC(5,2) NOT NULL DEFAULT 15.00,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- SECTION 3 — CUSTOMERS & PARTNERS
-- =============================================================================

CREATE TABLE customers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_type   TEXT NOT NULL CHECK (customer_type IN ('individual','business')),
    full_name       TEXT,
    company_name    TEXT,
    contact_person  TEXT,
    phone           TEXT NOT NULL,
    email           TEXT,
    address         TEXT,
    tax_code        TEXT,
    current_debt    NUMERIC(12,2) NOT NULL DEFAULT 0,
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE partners (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name    TEXT NOT NULL,
    contact_person  TEXT,
    phone           TEXT,
    email           TEXT,
    address         TEXT,
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- SECTION 4 — ORDERS & SHIPMENTS
-- =============================================================================

CREATE TABLE orders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id         BIGINT REFERENCES customers(id),
    created_by          BIGINT NOT NULL REFERENCES profiles(id),
    cargo_name          TEXT,
    cargo_weight_kg     NUMERIC(10,2),
    pickup_address      TEXT NOT NULL,
    delivery_address    TEXT NOT NULL,
    estimated_price     NUMERIC(12,2),
    actual_price        NUMERIC(12,2),
    payment_type        TEXT CHECK (payment_type IN ('cash','bank_transfer','client_credit')),
    status              TEXT NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending','assigned','in_progress','completed','cancelled')),
    is_confidential     BOOLEAN NOT NULL DEFAULT FALSE,
    notes               TEXT,
    completed_at        TIMESTAMPTZ,
    updated_by          BIGINT REFERENCES profiles(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Each physical transport leg of an order
CREATE TABLE order_shipments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    shipment_index      SMALLINT NOT NULL,           -- 1-based; used to detect "final trip"
    vehicle_group_id    BIGINT NOT NULL REFERENCES vehicle_groups(id),  -- pool filter key
    owner_driver_id     BIGINT REFERENCES profiles(id),  -- current active driver
    pickup_address      TEXT NOT NULL,
    delivery_address    TEXT NOT NULL,
    cargo_weight_kg     NUMERIC(10,2),
    estimated_price     NUMERIC(12,2),
    actual_price        NUMERIC(12,2),
    status              TEXT NOT NULL DEFAULT 'available'
                            CHECK (status IN (
                                'available','claimed','picking','loaded',
                                'transit','arrived','completed','cancelled','failed','returning'
                            )),
    -- Atomic claim guard: version incremented on every status change
    -- App does: UPDATE ... SET status='claimed', version=version+1 WHERE id=? AND version=?
    version             INT NOT NULL DEFAULT 0,
    notes               TEXT,
    -- Lifecycle timestamps (nullable until reached)
    claimed_at          TIMESTAMPTZ,
    picking_at          TIMESTAMPTZ,
    loaded_at           TIMESTAMPTZ,
    transit_at          TIMESTAMPTZ,
    arrived_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    cancelled_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (order_id, shipment_index)
);

-- Who was assigned / self-claimed
CREATE TABLE shipment_assignments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id         BIGINT NOT NULL REFERENCES order_shipments(id) ON DELETE CASCADE,
    driver_id           BIGINT NOT NULL REFERENCES profiles(id),
    vehicle_id          BIGINT NOT NULL REFERENCES vehicles(id),
    assignment_type     TEXT NOT NULL CHECK (assignment_type IN ('coordinator_assign','self_claim')),
    assigned_by         BIGINT REFERENCES profiles(id),  -- NULL when self_claim
    assigned_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    accepted_at         TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ
);

-- =============================================================================
-- SECTION 5 — PAYMENTS PER SHIPMENT
-- Requirements: multiple payments per trip, each may have multiple receipts
-- =============================================================================

CREATE TABLE shipment_payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id     BIGINT NOT NULL REFERENCES order_shipments(id) ON DELETE CASCADE,
    payment_type    TEXT NOT NULL CHECK (payment_type IN ('cash_collected','bank_transfer','client_credit')),
    amount          NUMERIC(12,2) NOT NULL,
    collected_by    BIGINT REFERENCES profiles(id),  -- driver who collected
    collected_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Receipt images per payment (cash requires ≥1; bank optional; credit none)
CREATE TABLE payment_receipts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id      BIGINT NOT NULL REFERENCES shipment_payments(id) ON DELETE CASCADE,
    file_url        TEXT NOT NULL,
    uploaded_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- SECTION 6 — COMPLETION PROOF (final trip of order only)
-- Must be real-time captured (no upload from device allowed — enforced at app layer)
-- =============================================================================

CREATE TABLE completion_proofs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    shipment_id     BIGINT NOT NULL REFERENCES order_shipments(id),  -- must be final shipment
    captured_by     BIGINT NOT NULL REFERENCES profiles(id),
    -- is_realtime_capture enforced by app; stored here for audit
    is_realtime     BOOLEAN NOT NULL DEFAULT TRUE,
    file_url        TEXT NOT NULL,
    captured_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (order_id)   -- one proof per order
);

-- =============================================================================
-- SECTION 7 — EXPENSES
-- =============================================================================

CREATE TABLE expenses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id     BIGINT REFERENCES order_shipments(id),
    vehicle_id      BIGINT REFERENCES vehicles(id),
    created_by      BIGINT NOT NULL REFERENCES profiles(id),
    expense_type    TEXT NOT NULL
                        CHECK (expense_type IN ('fuel','toll','parking','repair','maintenance','depreciation','other')),
    amount          NUMERIC(12,2) NOT NULL,
    description     TEXT,
    expense_date    DATE NOT NULL DEFAULT CURRENT_DATE,
    updated_by      BIGINT REFERENCES profiles(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE expense_attachments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id  BIGINT NOT NULL REFERENCES expenses(id) ON DELETE CASCADE,
    file_url    TEXT NOT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- SECTION 8 — MAINTENANCE RECORDS
-- =============================================================================

CREATE TABLE maintenance_records (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id          BIGINT NOT NULL REFERENCES vehicles(id),
    expense_id          BIGINT REFERENCES expenses(id),
    maintenance_type    TEXT NOT NULL CHECK (maintenance_type IN ('scheduled','repair','inspection','emergency')),
    description         TEXT,
    cost                NUMERIC(12,2),
    maintenance_date    DATE NOT NULL,
    next_due_date       DATE,
    performed_by        TEXT,   -- workshop name / person
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- SECTION 9 — DEBTS & DEBT PAYMENTS
-- =============================================================================

CREATE TABLE debts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_type       TEXT NOT NULL CHECK (debt_type IN ('customer','partner','driver')),
    customer_id     BIGINT REFERENCES customers(id),
    partner_id      BIGINT REFERENCES partners(id),
    driver_id       BIGINT REFERENCES profiles(id),
    order_id        BIGINT REFERENCES orders(id),
    total_amount    NUMERIC(12,2) NOT NULL,
    paid_amount     NUMERIC(12,2) NOT NULL DEFAULT 0,
    due_date        DATE,
    status          TEXT NOT NULL DEFAULT 'unpaid'
                        CHECK (status IN ('unpaid','partial','paid','overdue')),
    notes           TEXT,
    updated_by      BIGINT REFERENCES profiles(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE debt_payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_id         BIGINT NOT NULL REFERENCES debts(id) ON DELETE CASCADE,
    amount          NUMERIC(12,2) NOT NULL,
    payment_method  TEXT CHECK (payment_method IN ('cash','bank_transfer','offset')),
    paid_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by      BIGINT NOT NULL REFERENCES profiles(id),
    notes           TEXT
);

-- =============================================================================
-- SECTION 10 — KPI RECORDS
-- =============================================================================

CREATE TABLE kpi_records (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id               BIGINT NOT NULL REFERENCES profiles(id),
    vehicle_group_id        BIGINT NOT NULL REFERENCES vehicle_groups(id),  -- for group leaderboard
    month                   SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12),
    year                    SMALLINT NOT NULL,
    completed_shipments     INT NOT NULL DEFAULT 0,
    total_revenue           NUMERIC(12,2) NOT NULL DEFAULT 0,
    late_deliveries         INT NOT NULL DEFAULT 0,
    incident_count          INT NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (driver_id, month, year)
);

-- =============================================================================
-- SECTION 11 — BONUS RULES & RECORDS
-- =============================================================================

CREATE TABLE bonus_rules (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_group_id    BIGINT REFERENCES vehicle_groups(id),  -- NULL = applies to all groups
    title               TEXT NOT NULL,
    bonus_type          TEXT NOT NULL CHECK (bonus_type IN ('kpi','top_driver','overtime','holiday','custom')),
    reward_amount       NUMERIC(12,2),
    reward_multiplier   NUMERIC(5,2),   -- e.g. 2.0 for 200% overtime pay
    conditions_json     JSONB,          -- flexible rule conditions
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE bonus_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id       BIGINT NOT NULL REFERENCES profiles(id),
    bonus_rule_id   BIGINT REFERENCES bonus_rules(id),
    amount          NUMERIC(12,2) NOT NULL,
    awarded_month   SMALLINT CHECK (awarded_month BETWEEN 1 AND 12),
    awarded_year    SMALLINT,
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- SECTION 12 — PAYROLL
-- Base salary: <12 months → 8,000,000; >=12 months → 9,000,000
-- Revenue bonus: 15% revenue share
-- BHXH: 32% total (split company/employee — stored separately for transparency)
-- =============================================================================

CREATE TABLE payrolls (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id                   BIGINT NOT NULL REFERENCES profiles(id),
    payroll_month               SMALLINT NOT NULL CHECK (payroll_month BETWEEN 1 AND 12),
    payroll_year                SMALLINT NOT NULL,

    -- Base
    base_salary                 NUMERIC(12,2) NOT NULL,   -- 8M or 9M depending on hire_date
    months_of_service           INT NOT NULL,              -- snapshot at generation time

    -- Revenue
    total_revenue               NUMERIC(12,2) NOT NULL DEFAULT 0,
    revenue_bonus               NUMERIC(12,2) NOT NULL DEFAULT 0,   -- 15% of total_revenue

    -- Bonuses (itemized for auditability)
    kpi_bonus                   NUMERIC(12,2) NOT NULL DEFAULT 0,
    top_driver_bonus            NUMERIC(12,2) NOT NULL DEFAULT 0,
    overtime_bonus              NUMERIC(12,2) NOT NULL DEFAULT 0,
    holiday_bonus               NUMERIC(12,2) NOT NULL DEFAULT 0,
    other_bonus                 NUMERIC(12,2) NOT NULL DEFAULT 0,

    -- Deductions (itemized)
    insurance_employee          NUMERIC(12,2) NOT NULL DEFAULT 0,   -- employee BHXH share
    insurance_company           NUMERIC(12,2) NOT NULL DEFAULT 0,   -- company BHXH share (cost center)
    advance_deduction           NUMERIC(12,2) NOT NULL DEFAULT 0,   -- salary advances repaid
    absence_penalty             NUMERIC(12,2) NOT NULL DEFAULT 0,
    other_deduction             NUMERIC(12,2) NOT NULL DEFAULT 0,

    -- Totals
    gross_salary                NUMERIC(12,2) GENERATED ALWAYS AS (
                                    base_salary
                                    + revenue_bonus
                                    + kpi_bonus + top_driver_bonus
                                    + overtime_bonus + holiday_bonus + other_bonus
                                ) STORED,
    net_salary                  NUMERIC(12,2) GENERATED ALWAYS AS (
                                    base_salary
                                    + revenue_bonus
                                    + kpi_bonus + top_driver_bonus
                                    + overtime_bonus + holiday_bonus + other_bonus
                                    - insurance_employee
                                    - advance_deduction
                                    - absence_penalty
                                    - other_deduction
                                ) STORED,

    -- Workflow: pending → reviewed → approved → paid
    status                      TEXT NOT NULL DEFAULT 'pending'
                                    CHECK (status IN ('pending','reviewed','approved','paid')),
    reviewed_by                 BIGINT REFERENCES profiles(id),   -- Accountant
    reviewed_at                 TIMESTAMPTZ,
    approved_by                 BIGINT REFERENCES profiles(id),   -- Manager
    approved_at                 TIMESTAMPTZ,
    paid_by                     BIGINT REFERENCES profiles(id),
    paid_at                     TIMESTAMPTZ,

    UNIQUE (driver_id, payroll_month, payroll_year),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- SECTION 13 — SALARY ADVANCES
-- Workflow: Driver request → Accountant review → Manager approve/reject → Accountant pay
-- =============================================================================

CREATE TABLE salary_advances (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id       BIGINT NOT NULL REFERENCES profiles(id),
    amount          NUMERIC(12,2) NOT NULL,
    reason          TEXT,
    request_month   SMALLINT NOT NULL CHECK (request_month BETWEEN 1 AND 12),
    request_year    SMALLINT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','approved','rejected','paid')),
    reviewed_by     BIGINT REFERENCES profiles(id),   -- Accountant
    reviewed_at     TIMESTAMPTZ,
    approved_by     BIGINT REFERENCES profiles(id),   -- Manager
    approved_at     TIMESTAMPTZ,
    paid_by         BIGINT REFERENCES profiles(id),   -- Accountant
    paid_at         TIMESTAMPTZ,
    reject_reason   TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- SECTION 14 — INCIDENTS
-- =============================================================================

CREATE TABLE incidents (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id     BIGINT NOT NULL REFERENCES order_shipments(id) ON DELETE CASCADE,
    reported_by     BIGINT NOT NULL REFERENCES profiles(id),
    incident_type   TEXT NOT NULL
                        CHECK (incident_type IN ('vehicle_breakdown','cargo_damage','road_incident','other')),
    severity_level  TEXT NOT NULL DEFAULT 'medium'
                        CHECK (severity_level IN ('low','medium','high','critical')),
    description     TEXT NOT NULL,
    location        TEXT,
    estimated_loss  NUMERIC(12,2) DEFAULT 0,
    status          TEXT NOT NULL DEFAULT 'open'
                        CHECK (status IN ('open','investigating','resolved','closed')),
    occurred_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Separate table for evidence images (replaces TEXT[] anti-pattern)
CREATE TABLE incident_evidences (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id     BIGINT NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,
    file_url        TEXT NOT NULL,
    uploaded_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- SECTION 15 — NOTIFICATIONS
-- =============================================================================

CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    title       TEXT NOT NULL,
    body        TEXT,
    type        TEXT,   -- e.g. 'trip_assigned', 'payroll_approved', 'incident_reported'
    entity_type TEXT,   -- e.g. 'order_shipments'
    entity_id   BIGINT,
    is_read     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- SECTION 16 — ACTIVITY LOGS (audit trail)
-- =============================================================================

CREATE TABLE activity_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT REFERENCES profiles(id),   -- NULL if system-generated
    action      TEXT NOT NULL,       -- e.g. 'shipment.status_changed', 'payroll.approved'
    entity_type TEXT NOT NULL,
    entity_id   BIGINT,
    old_data    JSONB,               -- snapshot before change
    new_data    JSONB,               -- snapshot after change
    ip_address  INET,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- INDEXES
-- Focus: hot query paths — status filters, FK lookups, driver queries, group filters
-- =============================================================================

-- accounts
CREATE INDEX idx_accounts_email ON accounts(email);

-- profiles
CREATE INDEX idx_profiles_role_id ON profiles(role_id);

-- orders
CREATE INDEX idx_orders_customer_id    ON orders(customer_id);
CREATE INDEX idx_orders_status         ON orders(status);
CREATE INDEX idx_orders_created_by     ON orders(created_by);
CREATE INDEX idx_orders_created_at     ON orders(created_at DESC);

-- order_shipments (most queried table)
CREATE INDEX idx_shipments_order_id          ON order_shipments(order_id);
CREATE INDEX idx_shipments_status            ON order_shipments(status);
CREATE INDEX idx_shipments_owner_driver_id   ON order_shipments(owner_driver_id);
CREATE INDEX idx_shipments_vehicle_group_id  ON order_shipments(vehicle_group_id);
-- Pool query: available trips for a driver's vehicle_group
CREATE INDEX idx_shipments_pool ON order_shipments(vehicle_group_id, status)
    WHERE status = 'available';

-- shipment_assignments
CREATE INDEX idx_assignments_shipment_id ON shipment_assignments(shipment_id);
CREATE INDEX idx_assignments_driver_id   ON shipment_assignments(driver_id);

-- shipment_payments
CREATE INDEX idx_spayments_shipment_id ON shipment_payments(shipment_id);

-- expenses
CREATE INDEX idx_expenses_shipment_id ON expenses(shipment_id);
CREATE INDEX idx_expenses_vehicle_id  ON expenses(vehicle_id);
CREATE INDEX idx_expenses_created_by  ON expenses(created_by);

-- debts
CREATE INDEX idx_debts_status      ON debts(status);
CREATE INDEX idx_debts_customer_id ON debts(customer_id);
CREATE INDEX idx_debts_driver_id   ON debts(driver_id);

-- kpi_records
CREATE INDEX idx_kpi_driver_month_year   ON kpi_records(driver_id, year, month);
CREATE INDEX idx_kpi_group_month_year    ON kpi_records(vehicle_group_id, year, month);

-- payrolls
CREATE INDEX idx_payrolls_driver_id    ON payrolls(driver_id);
CREATE INDEX idx_payrolls_status       ON payrolls(status);
CREATE INDEX idx_payrolls_month_year   ON payrolls(payroll_year, payroll_month);

-- salary_advances
CREATE INDEX idx_advances_driver_id ON salary_advances(driver_id);
CREATE INDEX idx_advances_status    ON salary_advances(status);

-- incidents
CREATE INDEX idx_incidents_shipment_id ON incidents(shipment_id);
CREATE INDEX idx_incidents_status      ON incidents(status);

-- notifications
CREATE INDEX idx_notifications_user_id  ON notifications(user_id);
CREATE INDEX idx_notifications_unread   ON notifications(user_id) WHERE is_read = FALSE;

-- activity_logs
CREATE INDEX idx_logs_user_id     ON activity_logs(user_id);
CREATE INDEX idx_logs_entity      ON activity_logs(entity_type, entity_id);
CREATE INDEX idx_logs_created_at  ON activity_logs(created_at DESC);

-- vehicles
CREATE INDEX idx_vehicles_group_id ON vehicles(vehicle_group_id);
CREATE INDEX idx_vehicles_status   ON vehicles(status);

-- maintenance
CREATE INDEX idx_maintenance_vehicle_id ON maintenance_records(vehicle_id);