-- Clean up schema
DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

-- Enable pgcrypto extension for secure password hashing
CREATE EXTENSION IF NOT EXISTS pgcrypto;

--------------------------------------------------------------------------------
-- 1. AUTHENTICATION & USER MANAGEMENT
--------------------------------------------------------------------------------

-- Custom EDB replacement for Supabase auth.users
CREATE TABLE accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL, -- To store hashed passwords using crypt()
    is_verified BOOLEAN DEFAULT FALSE,
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

INSERT INTO roles (id, name)
VALUES
(1, 'admin'),
(2, 'coordinator'),
(3, 'accountant'),
(4, 'driver');

CREATE TABLE profiles (
    id INT PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE,
    phone TEXT UNIQUE,
    role_id INT REFERENCES roles(id),
    avatar_url TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

--------------------------------------------------------------------------------
-- 2. CORE LOGISTICS & FLEET ENTITIES
--------------------------------------------------------------------------------

CREATE TABLE customers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_type TEXT NOT NULL CHECK (customer_type IN ('individual', 'business')),
    full_name TEXT,
    company_name TEXT,
    contact_person TEXT,
    phone TEXT NOT NULL,
    email TEXT,
    address TEXT,
    tax_code TEXT,
    current_debt NUMERIC(12,2) DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE vehicle_groups (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    max_load_weight NUMERIC(10,2),
    fixed_price_per_km NUMERIC(12,2) NOT NULL,
    depreciation_per_km NUMERIC(10,2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE vehicles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number TEXT UNIQUE NOT NULL,
    vehicle_group_id INT REFERENCES vehicle_groups(id),
    brand TEXT,
    model TEXT,
    load_capacity NUMERIC(10,2),
    manufacture_year INT,
    assigned_driver_id INT REFERENCES profiles(id), -- Changed from UUID
    status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'in_delivery', 'maintenance', 'inactive')),
    purchase_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE drivers (
    profile_id INT PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE, -- Changed from UUID
    license_number TEXT NOT NULL,
    license_expiry_date DATE,
    base_salary NUMERIC(12,2) DEFAULT 0,
    revenue_share_percent NUMERIC(5,2) DEFAULT 15,
    joined_at DATE,
    emergency_contact TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE partners (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    contact_person TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

--------------------------------------------------------------------------------
-- 3. ORDERS & SHIPMENTS
--------------------------------------------------------------------------------

CREATE TABLE orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT REFERENCES customers(id),
    created_by INT REFERENCES profiles(id), -- Changed from UUID
    cargo_name TEXT,
    cargo_weight NUMERIC(10,2),
    pickup_address TEXT NOT NULL,
    delivery_address TEXT NOT NULL,
    estimated_price NUMERIC(12,2),
    actual_price NUMERIC(12,2),
    payment_type TEXT CHECK (payment_type IN ('cash', 'bank_transfer', 'debt')),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'assigned', 'in_progress', 'completed', 'cancelled')),
    is_confidential BOOLEAN DEFAULT false,
    notes TEXT,
    updated_by INT REFERENCES profiles(id), -- Changed from UUID
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE order_shipments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    shipment_index INT NOT NULL,
    pickup_address TEXT,
    delivery_address TEXT,
    cargo_weight NUMERIC(10,2),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'picked_up', 'delivered', 'confirmed', 'cancelled')),
    actual_delivery_time TIMESTAMPTZ,
    customer_confirmed BOOLEAN DEFAULT false,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE shipment_assignments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id INT REFERENCES order_shipments(id) ON DELETE CASCADE,
    driver_id INT REFERENCES profiles(id), -- Changed from UUID
    vehicle_id INT REFERENCES vehicles(id),
    assigned_at TIMESTAMPTZ DEFAULT NOW(),
    accepted_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);

--------------------------------------------------------------------------------
-- 4. FINANCE, PAYROLL, & MAINTENANCE
--------------------------------------------------------------------------------

CREATE TABLE expenses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id INT REFERENCES order_shipments(id),
    vehicle_id INT REFERENCES vehicles(id),
    created_by INT REFERENCES profiles(id), -- Changed from UUID
    expense_type TEXT NOT NULL CHECK (expense_type IN ('fuel', 'toll', 'parking', 'maintenance', 'repair', 'depreciation', 'other')),
    amount NUMERIC(12,2) NOT NULL,
    description TEXT,
    expense_date TIMESTAMPTZ DEFAULT NOW(),
    updated_by INT REFERENCES profiles(id), -- Changed from UUID
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE expense_attachments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id INT REFERENCES expenses(id) ON DELETE CASCADE,
    file_url TEXT NOT NULL,
    uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE debts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_type TEXT NOT NULL CHECK (debt_type IN ('customer', 'partner', 'driver')),
    customer_id INT REFERENCES customers(id),
    partner_id INT REFERENCES partners(id),
    driver_id INT REFERENCES profiles(id), -- Changed from UUID
    order_id INT REFERENCES orders(id),
    total_amount NUMERIC(12,2) NOT NULL,
    paid_amount NUMERIC(12,2) DEFAULT 0,
    due_date DATE,
    status TEXT DEFAULT 'unpaid' CHECK (status IN ('unpaid', 'partial', 'paid', 'overdue')),
    notes TEXT,
    updated_by INT REFERENCES profiles(id), -- Changed from UUID
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE payments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_id INT REFERENCES debts(id) ON DELETE CASCADE,
    amount NUMERIC(12,2) NOT NULL,
    payment_method TEXT,
    paid_at TIMESTAMPTZ DEFAULT NOW(),
    created_by INT REFERENCES profiles(id), -- Changed from UUID
    notes TEXT
);

CREATE TABLE payrolls (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id INT REFERENCES profiles(id), -- Changed from UUID
    payroll_month INT NOT NULL,
    payroll_year INT NOT NULL,
    base_salary NUMERIC(12,2),
    revenue_bonus NUMERIC(12,2),
    extra_bonus NUMERIC(12,2),
    deduction NUMERIC(12,2),
    total_salary NUMERIC(12,2),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'paid')),
    updated_by INT REFERENCES profiles(id), -- Changed from UUID
    UNIQUE(driver_id, payroll_month, payroll_year),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE kpi_records (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id INT REFERENCES profiles(id), -- Changed from UUID
    month INT NOT NULL,
    year INT NOT NULL,
    completed_shipments INT DEFAULT 0,
    total_revenue NUMERIC(12,2) DEFAULT 0,
    late_deliveries INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE bonus_rules (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_group_id INT REFERENCES vehicle_groups(id),
    title TEXT NOT NULL,
    reward_amount NUMERIC(12,2),
    conditions TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE bonus_records (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id INT REFERENCES profiles(id), -- Changed from UUID
    bonus_rule_id INT REFERENCES bonus_rules(id),
    amount NUMERIC(12,2),
    awarded_month INT,
    awarded_year INT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE maintenance_records (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id INT REFERENCES vehicles(id),
    maintenance_type TEXT,
    expense_id INT REFERENCES expenses(id),
    description TEXT,
    cost NUMERIC(12,2),
    maintenance_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

--------------------------------------------------------------------------------
-- 5. NOTIFICATIONS, LOGS, & INCIDENTS
--------------------------------------------------------------------------------

CREATE TABLE notifications (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES profiles(id), -- Changed from UUID
    title TEXT NOT NULL,
    content TEXT,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE activity_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES profiles(id), -- Changed from UUID
    action TEXT NOT NULL,
    entity_type TEXT,
    entity_id TEXT, -- Kept as text to accept general primary keys
    metadata JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE incidents (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id INT REFERENCES order_shipments(id) ON DELETE CASCADE,
    reported_by INT REFERENCES profiles(id), -- Changed from UUID
    incident_type TEXT NOT NULL CHECK (incident_type IN ('traffic_accident', 'vehicle_breakdown', 'cargo_damage', 'weather_delay', 'customer_refusal', 'other')),
    severity_level TEXT DEFAULT 'medium' CHECK (severity_level IN ('low', 'medium', 'high', 'critical')),
    description TEXT NOT NULL,
    location TEXT,
    estimated_loss NUMERIC(12,2) DEFAULT 0,
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'investigating', 'resolved', 'closed')),
    evidence_urls TEXT[], 
    occurred_at TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

--------------------------------------------------------------------------------
-- 6. PERFORMANCE INDEXES
--------------------------------------------------------------------------------

CREATE INDEX idx_incidents_shipment_id ON incidents(shipment_id);
CREATE INDEX idx_orders_customer_id ON orders(customer_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_created_by ON orders(created_by);
CREATE INDEX idx_shipments_order_id ON order_shipments(order_id);
CREATE INDEX idx_shipments_status ON order_shipments(status);
CREATE INDEX idx_expenses_shipment_id ON expenses(shipment_id);
CREATE INDEX idx_expenses_vehicle_id ON expenses(vehicle_id);
CREATE INDEX idx_debts_status ON debts(status);