-- Migration 2026-07-12: Lịch sử gán xe cho driver
-- Ghi lại mỗi lần gán / bỏ gán driver khỏi xe (audit theo spec §27).

BEGIN;

CREATE TABLE IF NOT EXISTS vehicle_driver_assignments (
    id                  INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    vehicle_id          INT NOT NULL REFERENCES vehicles(id),
    driver_id           INT REFERENCES profiles(id),   -- NULL khi bỏ gán
    previous_driver_id  INT REFERENCES profiles(id),   -- driver trước đó (NULL nếu xe đang trống)
    action              TEXT NOT NULL CHECK (action IN ('assign','unassign')),
    note                TEXT,
    created_by          INT REFERENCES profiles(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vda_vehicle ON vehicle_driver_assignments(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_vda_driver  ON vehicle_driver_assignments(driver_id);
CREATE INDEX IF NOT EXISTS idx_vda_prev_driver ON vehicle_driver_assignments(previous_driver_id);

COMMIT;
