-- =============================================================================
-- SEED DATA — SEP490 Logistics System
-- Chạy tự động SAU "DB script.sql" khi khởi động Docker
-- Bao gồm: dữ liệu cơ bản + data test đầy đủ cho driver module
-- =============================================================================

-- =============================================================================
-- SECTION 0: SCHEMA MIGRATIONS
-- Các cột bổ sung cho debt_payments và bảng leave_requests
-- Dùng IF NOT EXISTS để an toàn khi chạy lại
-- =============================================================================

ALTER TABLE debt_payments ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','confirmed','rejected'));
ALTER TABLE debt_payments ADD COLUMN IF NOT EXISTS receipt_url TEXT;
ALTER TABLE debt_payments ADD COLUMN IF NOT EXISTS reject_reason TEXT;
ALTER TABLE debt_payments ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMPTZ;
ALTER TABLE debt_payments ADD COLUMN IF NOT EXISTS confirmed_by INT REFERENCES profiles(id);

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS dob DATE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS country TEXT NOT NULL DEFAULT 'VN';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'profiles_gender_check'
    ) THEN
        ALTER TABLE profiles
            ADD CONSTRAINT profiles_gender_check
            CHECK (gender IN ('male', 'female', 'other'));
    END IF;
END $$;


DROP TABLE IF EXISTS bills CASCADE;

CREATE TABLE IF NOT EXISTS leave_requests (
    id          INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    driver_id   INT NOT NULL REFERENCES profiles(id),
    leave_date  DATE NOT NULL,
    leave_type  TEXT NOT NULL DEFAULT 'unpaid'
                    CHECK (leave_type IN ('paid', 'unpaid')),
    reason      TEXT,
    status      TEXT NOT NULL DEFAULT 'approved'
                    CHECK (status IN ('approved', 'rejected')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (driver_id, leave_date)
);

-- =============================================================================
-- SECTION 1: ROLES
-- =============================================================================
INSERT INTO roles (name) VALUES
    ('manager'), ('coordinator'), ('accountant'), ('driver')
ON CONFLICT (name) DO NOTHING;

-- =============================================================================
-- SECTION 2: ACCOUNTS
-- =============================================================================
INSERT INTO accounts (email, password_hash, role_id, is_active) VALUES
    ('admin@example.com',       crypt('admin123',  gen_salt('bf')), (SELECT id FROM roles WHERE name = 'manager'),     TRUE),
    ('ntck005@gmail.com',       crypt('coord123',  gen_salt('bf')), (SELECT id FROM roles WHERE name = 'coordinator'), TRUE),
    ('accountant@example.com',  crypt('acct123',   gen_salt('bf')), (SELECT id FROM roles WHERE name = 'accountant'),  TRUE),
    ('driver1@example.com',     crypt('driver123', gen_salt('bf')), (SELECT id FROM roles WHERE name = 'driver'),      TRUE),
    ('driver2@example.com',     crypt('driver123', gen_salt('bf')), (SELECT id FROM roles WHERE name = 'driver'),      TRUE),
    ('driver3@example.com',     crypt('driver123', gen_salt('bf')), (SELECT id FROM roles WHERE name = 'driver'),      TRUE),
    ('driver4@example.com',     crypt('driver123', gen_salt('bf')), (SELECT id FROM roles WHERE name = 'driver'),      TRUE)
ON CONFLICT (email) DO UPDATE
    SET password_hash = EXCLUDED.password_hash,
        role_id       = EXCLUDED.role_id,
        is_active     = EXCLUDED.is_active;

-- =============================================================================
-- SECTION 3: PROFILES
-- =============================================================================
WITH account_data AS (
    SELECT id, email FROM accounts
    WHERE email IN (
        'admin@example.com', 'ntck005@gmail.com', 'accountant@example.com',
        'driver1@example.com', 'driver2@example.com', 'driver3@example.com', 'driver4@example.com'
    )
)
INSERT INTO profiles (id, full_name, phone, role_id, dob, gender, address, city, country)
VALUES
    ((SELECT id FROM account_data WHERE email = 'admin@example.com'),       'Manager',            '0901234560', (SELECT id FROM roles WHERE name = 'manager'),     DATE '1988-05-12', 'male',   '12 Nguyen Hue, District 1',        'Ho Chi Minh', 'VN'),
    ((SELECT id FROM account_data WHERE email = 'ntck005@gmail.com'),       'Nguyen Coordinator', '0901234561', (SELECT id FROM roles WHERE name = 'coordinator'), DATE '1992-09-21', 'female', '88 Le Loi, Hai Chau',               'Da Nang',     'VN'),
    ((SELECT id FROM account_data WHERE email = 'accountant@example.com'),  'Tran Accountant',    '0901234562', (SELECT id FROM roles WHERE name = 'accountant'),  DATE '1991-03-14', 'female', '25 Vo Thi Sau, Ninh Kieu',          'Can Tho',     'VN'),
    ((SELECT id FROM account_data WHERE email = 'driver1@example.com'),     'Le Driver 1',        '0901234563', (SELECT id FROM roles WHERE name = 'driver'),      DATE '1995-07-08', 'male',   '101 Tran Hung Dao, Thu Duc',        'Ho Chi Minh', 'VN'),
    ((SELECT id FROM account_data WHERE email = 'driver2@example.com'),     'Pham Driver 2',      '0901234564', (SELECT id FROM roles WHERE name = 'driver'),      DATE '1994-11-02', 'male',   '55 Hung Vuong, Thanh Khe',          'Da Nang',     'VN'),
    ((SELECT id FROM account_data WHERE email = 'driver3@example.com'),     'Do Driver 3',        '0901234565', (SELECT id FROM roles WHERE name = 'driver'),      DATE '1997-01-18', 'other',  '7 Nguyen Van Cu, Ninh Kieu',        'Can Tho',     'VN'),
    ((SELECT id FROM account_data WHERE email = 'driver4@example.com'),     'Vo Driver 4',        '0901234566', (SELECT id FROM roles WHERE name = 'driver'),      DATE '1990-12-27', 'male',   '240 Le Duan, Hai Chau',             'Da Nang',     'VN')
ON CONFLICT (id) DO UPDATE
    SET full_name = EXCLUDED.full_name,
        phone = EXCLUDED.phone,
        role_id = EXCLUDED.role_id,
        dob = EXCLUDED.dob,
        gender = EXCLUDED.gender,
        address = EXCLUDED.address,
        city = EXCLUDED.city,
        country = EXCLUDED.country;

-- =============================================================================
-- SECTION 4: DRIVERS
-- =============================================================================
WITH driver_seed AS (
    SELECT * FROM (VALUES
        ('driver1@example.com', 'DL123456', DATE '2027-12-31', DATE '2023-01-01', 15.00::NUMERIC),
        ('driver2@example.com', 'DL223456', DATE '2028-06-30', DATE '2023-07-15', 15.00::NUMERIC),
        ('driver3@example.com', 'DL323456', DATE '2028-11-15', DATE '2024-02-20', 15.00::NUMERIC),
        ('driver4@example.com', 'DL423456', DATE '2029-04-10', DATE '2022-09-05', 16.50::NUMERIC)
    ) AS seeded(email, license_number, license_expiry_date, hire_date, revenue_share_percent)
)
INSERT INTO drivers (profile_id, license_number, license_expiry_date, hire_date, revenue_share_percent)
SELECT p.id, ds.license_number, ds.license_expiry_date, ds.hire_date, ds.revenue_share_percent
FROM driver_seed ds
JOIN accounts a ON a.email = ds.email
JOIN profiles p ON p.id = a.id
ON CONFLICT (profile_id) DO NOTHING;

-- =============================================================================
-- SECTION 5: CUSTOMERS
-- =============================================================================
INSERT INTO customers (customer_type, full_name, phone, email, address, current_debt)
SELECT 'individual', 'Nguyen Hoang Anh', '0987654321', 'anh@email.com', '123 Nguyen Hue, HCMC', 0
WHERE NOT EXISTS (SELECT 1 FROM customers WHERE phone = '0987654321');

INSERT INTO customers (customer_type, full_name, phone, email, address, current_debt)
SELECT 'business', 'ABC Logistics Co.', '0987654322', 'contact@abclogistics.vn', '456 Le Loi, HCMC', 500000
WHERE NOT EXISTS (SELECT 1 FROM customers WHERE phone = '0987654322');

INSERT INTO customers (customer_type, full_name, phone, email, address, current_debt)
SELECT 'individual', 'Tran Van Binh', '0987654323', 'binh@email.com', '789 Tran Hung Dao, HCMC', 0
WHERE NOT EXISTS (SELECT 1 FROM customers WHERE phone = '0987654323');

INSERT INTO customers (customer_type, full_name, phone, email, address, current_debt)
SELECT 'business', 'XYZ Trading', '0987654324', 'sales@xyztrading.vn', '321 Nguyen Trai, HCMC', 1000000
WHERE NOT EXISTS (SELECT 1 FROM customers WHERE phone = '0987654324');

-- =============================================================================
-- SECTION 6: VEHICLE GROUPS
-- =============================================================================
INSERT INTO vehicle_groups (name, max_load_weight_kg, price_per_km)
SELECT 'Small Van (1-2 tấn)', 2000, 10000
WHERE NOT EXISTS (SELECT 1 FROM vehicle_groups WHERE name = 'Small Van (1-2 tấn)');

INSERT INTO vehicle_groups (name, max_load_weight_kg, price_per_km)
SELECT 'Medium Truck (2-5 tấn)', 5000, 15000
WHERE NOT EXISTS (SELECT 1 FROM vehicle_groups WHERE name = 'Medium Truck (2-5 tấn)');

INSERT INTO vehicle_groups (name, max_load_weight_kg, price_per_km)
SELECT 'Large Truck (5-10 tấn)', 10000, 25000
WHERE NOT EXISTS (SELECT 1 FROM vehicle_groups WHERE name = 'Large Truck (5-10 tấn)');

-- =============================================================================
-- SECTION 7: VEHICLES
-- =============================================================================
INSERT INTO vehicles (plate_number, vehicle_group_id, brand, model, load_capacity_kg, manufacture_year, status) VALUES
    ('51-A12345', (SELECT id FROM vehicle_groups ORDER BY id ASC LIMIT 1), 'Toyota',  'Hiace',   2000,  2021, 'active'),
    ('51-B67890', (SELECT id FROM vehicle_groups ORDER BY id ASC OFFSET 1 LIMIT 1), 'Hino',    'FC',      5000,  2020, 'active'),
    ('51-C11111', (SELECT id FROM vehicle_groups ORDER BY id ASC OFFSET 2 LIMIT 1), 'Hyundai', 'HD120S',  10000, 2019, 'maintenance'),
    ('51-D22222', (SELECT id FROM vehicle_groups ORDER BY id ASC LIMIT 1), 'Ford',    'Transit', 2000,  2022, 'active'),
    ('51-E33333', (SELECT id FROM vehicle_groups ORDER BY id ASC LIMIT 1), 'Kia',     'K200',    1800,  2023, 'active'),
    ('51-F44444', (SELECT id FROM vehicle_groups ORDER BY id ASC OFFSET 1 LIMIT 1), 'Isuzu',   'QKR',     3500,  2021, 'active')
ON CONFLICT (plate_number) DO NOTHING;

-- =============================================================================
-- SECTION 8: DRIVER ↔ VEHICLE ASSIGNMENT
-- =============================================================================
WITH dvs AS (
    SELECT * FROM (VALUES
        ('driver1@example.com', '51-A12345'),
        ('driver2@example.com', '51-D22222'),
        ('driver4@example.com', '51-F44444')
    ) AS t(email, plate_number)
)
UPDATE vehicles v
SET assigned_driver_id = p.id
FROM dvs JOIN accounts a ON a.email = dvs.email JOIN profiles p ON p.id = a.id
WHERE v.plate_number = dvs.plate_number
  AND v.assigned_driver_id IS DISTINCT FROM p.id;

WITH dvs AS (
    SELECT * FROM (VALUES
        ('driver1@example.com', '51-A12345'),
        ('driver2@example.com', '51-D22222'),
        ('driver4@example.com', '51-F44444')
    ) AS t(email, plate_number)
)
UPDATE drivers d
SET vehicle_id = v.id
FROM dvs JOIN accounts a ON a.email = dvs.email JOIN profiles p ON p.id = a.id JOIN vehicles v ON v.plate_number = dvs.plate_number
WHERE d.profile_id = p.id AND d.vehicle_id IS DISTINCT FROM v.id;

-- =============================================================================
-- SECTION 9: PARTNERS
-- =============================================================================
INSERT INTO partners (company_name, contact_person, phone, email, address)
SELECT 'Tech Express Logistics', 'Mr. Tuan', '0912345678', 'tuan@techexpress.vn', '100 Pasteur, HCMC'
WHERE NOT EXISTS (SELECT 1 FROM partners WHERE company_name = 'Tech Express Logistics');

INSERT INTO partners (company_name, contact_person, phone, email, address)
SELECT 'Green Delivery Co.', 'Ms. Hoa', '0912345679', 'hoa@greendelivery.vn', '200 Nguyen Trai, HCMC'
WHERE NOT EXISTS (SELECT 1 FROM partners WHERE company_name = 'Green Delivery Co.');

INSERT INTO partners (company_name, contact_person, phone, email, address)
SELECT 'FastFreight Vietnam', 'Mr. Long', '0912345680', 'long@fastfreight.vn', '300 Landmark 81, HCMC'
WHERE NOT EXISTS (SELECT 1 FROM partners WHERE company_name = 'FastFreight Vietnam');

-- Ensure order columns required by the current backend exist even if an old volume/schema is reused.
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS vehicle_group_id INT REFERENCES vehicle_groups(id);
ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS final_price NUMERIC(12,2) NOT NULL DEFAULT 0;

DO $$
DECLARE
    v_constraint_name TEXT;
BEGIN
    SELECT con.conname
    INTO v_constraint_name
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    WHERE rel.relname = 'orders'
      AND nsp.nspname = 'public'
      AND con.contype = 'c'
      AND pg_get_constraintdef(con.oid) LIKE '%payment_type%'
      AND pg_get_constraintdef(con.oid) NOT LIKE '%client_credit%';

    IF v_constraint_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE public.orders DROP CONSTRAINT %I', v_constraint_name);
        ALTER TABLE public.orders
            ADD CONSTRAINT orders_payment_type_check
            CHECK (payment_type IN ('cash', 'bank_transfer', 'client_credit'));
    END IF;
END $$;

-- =============================================================================
-- SECTION 10: BASE ORDERS (open + completed)
-- vehicle_group_id lưu trên orders, KHÔNG phải order_shipments
-- =============================================================================

-- Order 1: available trong trip pool
INSERT INTO orders (customer_id, created_by, cargo_name, cargo_weight_kg, total_estimated_price,
                    payment_type, vehicle_group_id, derived_status, notes)
SELECT c.id, p.id, 'Electronics Package', 50.0, 500000, 'cash',
       (SELECT id FROM vehicle_groups ORDER BY id ASC LIMIT 1), 'open', 'Fragile - Handle with care'
FROM customers c
JOIN profiles p ON p.role_id = (SELECT id FROM roles WHERE name = 'coordinator')
WHERE c.phone = '0987654321'
  AND NOT EXISTS (SELECT 1 FROM orders WHERE cargo_name = 'Electronics Package')
LIMIT 1;

-- Order 2: đã hoàn thành — driver history
INSERT INTO orders (customer_id, created_by, cargo_name, cargo_weight_kg, total_estimated_price,
                    payment_type, vehicle_group_id, derived_status, notes)
SELECT c.id, p.id, 'Furniture Set', 200.0, 1500000, 'bank_transfer',
       (SELECT id FROM vehicle_groups ORDER BY id ASC LIMIT 1), 'completed', 'Large furniture item'
FROM customers c
JOIN profiles p ON p.role_id = (SELECT id FROM roles WHERE name = 'coordinator')
WHERE c.phone = '0987654322'
  AND NOT EXISTS (SELECT 1 FROM orders WHERE cargo_name = 'Furniture Set')
LIMIT 1;

-- =============================================================================
-- SECTION 11: BASE SHIPMENTS + TRIP STOPS
-- =============================================================================

-- Shipment 1: available
INSERT INTO order_shipments (order_id, shipment_index, cargo_weight_kg, estimated_price, status)
SELECT o.id, 1, o.cargo_weight_kg, o.total_estimated_price, 'available'
FROM orders o
WHERE o.cargo_name = 'Electronics Package'
  AND NOT EXISTS (SELECT 1 FROM order_shipments os WHERE os.order_id = o.id AND os.shipment_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone)
SELECT os.id, 1, 'pickup', '123 Nguyen Hue, HCMC', 'Nguyen Hoang Anh', '0987654321'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Electronics Package' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address)
SELECT os.id, 2, 'delivery', '456 Le Loi, HCMC'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Electronics Package' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 2);

-- Shipment 2: completed — driver1
INSERT INTO order_shipments (order_id, shipment_index, owner_driver_id, cargo_weight_kg, estimated_price,
                              status, claimed_at, completed_at)
SELECT o.id, 1, drv.id, o.cargo_weight_kg, o.total_estimated_price, 'completed',
       NOW() - INTERVAL '2 days', NOW() - INTERVAL '1 day'
FROM orders o
JOIN accounts a ON a.email = 'driver1@example.com'
JOIN profiles drv ON drv.id = a.id
WHERE o.cargo_name = 'Furniture Set'
  AND NOT EXISTS (SELECT 1 FROM order_shipments os WHERE os.order_id = o.id AND os.shipment_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone, completed_at)
SELECT os.id, 1, 'pickup', '789 Tran Hung Dao, HCMC', 'Tran Van Binh', '0987654323', NOW() - INTERVAL '2 days'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Furniture Set' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, completed_at)
SELECT os.id, 2, 'delivery', '321 Nguyen Trai, HCMC', NOW() - INTERVAL '1 day'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Furniture Set' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 2);

-- =============================================================================
-- SECTION 12: SHIPMENT ASSIGNMENTS
-- =============================================================================
INSERT INTO shipment_assignments (shipment_id, driver_id, vehicle_id, assignment_type, assigned_at)
SELECT os.id, p.id, v.id, 'coordinator_assign', NOW()
FROM order_shipments os
JOIN profiles p ON p.role_id = (SELECT id FROM roles WHERE name = 'driver')
JOIN accounts a ON a.id = p.id AND a.email = 'driver1@example.com'
JOIN vehicles v ON v.plate_number = '51-A12345'
WHERE os.status = 'available'
  AND NOT EXISTS (SELECT 1 FROM shipment_assignments sa WHERE sa.shipment_id = os.id)
LIMIT 1;

-- =============================================================================
-- SECTION 13: BONUS RULES
-- =============================================================================

INSERT INTO bonus_rules (vehicle_group_id, title, bonus_type, reward_amount, conditions_json)
SELECT (SELECT id FROM vehicle_groups ORDER BY id ASC LIMIT 1),
       'Thưởng vượt KPI — Small Van', 'kpi', 2000000, '{"min_revenue": 50000000}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM bonus_rules
    WHERE bonus_type = 'kpi' AND vehicle_group_id = (SELECT id FROM vehicle_groups ORDER BY id ASC LIMIT 1));

INSERT INTO bonus_rules (vehicle_group_id, title, bonus_type, reward_amount, conditions_json)
SELECT (SELECT id FROM vehicle_groups ORDER BY id ASC OFFSET 1 LIMIT 1),
       'Thưởng vượt KPI — Medium Truck', 'kpi', 2000000, '{"min_revenue": 65000000}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM bonus_rules
    WHERE bonus_type = 'kpi' AND vehicle_group_id = (SELECT id FROM vehicle_groups ORDER BY id ASC OFFSET 1 LIMIT 1));

INSERT INTO bonus_rules (vehicle_group_id, title, bonus_type, reward_amount, conditions_json)
SELECT (SELECT id FROM vehicle_groups ORDER BY id ASC OFFSET 2 LIMIT 1),
       'Thưởng vượt KPI — Large Truck', 'kpi', 2000000, '{"min_revenue": 70000000}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM bonus_rules
    WHERE bonus_type = 'kpi' AND vehicle_group_id = (SELECT id FROM vehicle_groups ORDER BY id ASC OFFSET 2 LIMIT 1));

INSERT INTO bonus_rules (vehicle_group_id, title, bonus_type, reward_amount, conditions_json)
SELECT (SELECT id FROM vehicle_groups ORDER BY id ASC LIMIT 1),
       'Lái xe xuất sắc nhất tháng — Small Van', 'top_revenue', 1000000, '{"rank": 1}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM bonus_rules
    WHERE bonus_type = 'top_revenue' AND vehicle_group_id = (SELECT id FROM vehicle_groups ORDER BY id ASC LIMIT 1));

INSERT INTO bonus_rules (vehicle_group_id, title, bonus_type, reward_amount, conditions_json)
SELECT (SELECT id FROM vehicle_groups ORDER BY id ASC OFFSET 1 LIMIT 1),
       'Lái xe xuất sắc nhất tháng — Medium Truck', 'top_revenue', 1000000, '{"rank": 1}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM bonus_rules
    WHERE bonus_type = 'top_revenue' AND vehicle_group_id = (SELECT id FROM vehicle_groups ORDER BY id ASC OFFSET 1 LIMIT 1));

INSERT INTO bonus_rules (vehicle_group_id, title, bonus_type, reward_amount, conditions_json)
SELECT (SELECT id FROM vehicle_groups ORDER BY id ASC OFFSET 2 LIMIT 1),
       'Lái xe xuất sắc nhất tháng — Large Truck', 'top_revenue', 1000000, '{"rank": 1}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM bonus_rules
    WHERE bonus_type = 'top_revenue' AND vehicle_group_id = (SELECT id FROM vehicle_groups ORDER BY id ASC OFFSET 2 LIMIT 1));

-- =============================================================================
-- SECTION 14: KPI RECORDS (base)
-- =============================================================================
INSERT INTO kpi_records (driver_id, vehicle_group_id, month, year, completed_shipments, total_revenue)
SELECT p.id, (SELECT id FROM vehicle_groups ORDER BY id ASC LIMIT 1), 5, 2026, 12, 15000000
FROM profiles p JOIN accounts a ON a.id = p.id
WHERE a.email = 'driver1@example.com'
ON CONFLICT DO NOTHING;

-- =============================================================================
-- SECTION 15: MAINTENANCE
-- =============================================================================
INSERT INTO maintenance_records (vehicle_id, maintenance_type, description, cost,
                                  maintenance_date, performed_by, status, started_at, created_at, updated_at)
SELECT v.id, 'scheduled', 'Oil change, filter replacement', 500000, '2026-05-15',
       p.id, 'open', NOW() - INTERVAL '24 days', NOW() - INTERVAL '24 days', NOW() - INTERVAL '24 days'
FROM vehicles v
JOIN accounts a ON a.email = 'driver3@example.com'
JOIN profiles p ON p.id = a.id
WHERE v.plate_number = '51-C11111'
  AND NOT EXISTS (SELECT 1 FROM maintenance_records mr WHERE mr.vehicle_id = v.id AND mr.maintenance_date = '2026-05-15');

INSERT INTO vehicle_status_history (vehicle_id, action_type, from_status, to_status, note, created_at)
SELECT v.id, 'send_to_maintenance', 'active', 'maintenance', 'Seeded maintenance workflow', NOW() - INTERVAL '24 days'
FROM vehicles v
WHERE v.plate_number = '51-C11111'
  AND NOT EXISTS (SELECT 1 FROM vehicle_status_history vsh WHERE vsh.vehicle_id = v.id AND vsh.action_type = 'send_to_maintenance');

-- =============================================================================
-- SECTION 16: RECEIPT REQUESTS (phiếu thu pending — coordinator xử lý)
-- =============================================================================
DO $$
DECLARE
    v_coordinator_id   INT;
    v_driver_id        INT;
    v_customer_id      INT;
    v_vehicle_id       INT;
    v_vehicle_group_id INT;
    v_order_id         INT;
    v_shipment_id      INT;
BEGIN
    SELECT p.id INTO v_coordinator_id
    FROM profiles p JOIN accounts a ON a.id = p.id
    WHERE a.email = 'ntck005@gmail.com';

    SELECT p.id INTO v_driver_id
    FROM profiles p JOIN accounts a ON a.id = p.id
    WHERE a.email = 'driver1@example.com';

    SELECT v.id, v.vehicle_group_id INTO v_vehicle_id, v_vehicle_group_id
    FROM vehicles v
    WHERE v.plate_number = '51-A12345';

    SELECT c.id INTO v_customer_id
    FROM customers c
    WHERE c.phone = '0987654322';

    IF NOT EXISTS (
        SELECT 1 FROM orders WHERE cargo_name = 'Receipt Pending Demo: Showroom Cabinets'
    ) THEN
        INSERT INTO orders (
            customer_id, created_by, cargo_name, cargo_weight_kg,
            total_estimated_price, payment_type, vehicle_group_id,
            derived_status, notes
        )
        VALUES (
            v_customer_id, v_coordinator_id, 'Receipt Pending Demo: Showroom Cabinets', 180.0,
            220000, 'cash', v_vehicle_group_id,
            'completed', 'Completed shipment waiting for coordinator receipt publishing'
        )
        RETURNING id INTO v_order_id;
    ELSE
        SELECT id INTO v_order_id
        FROM orders
        WHERE cargo_name = 'Receipt Pending Demo: Showroom Cabinets'
        LIMIT 1;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM order_shipments WHERE order_id = v_order_id AND shipment_index = 1
    ) THEN
        INSERT INTO order_shipments (
            order_id, shipment_index, owner_driver_id, vehicle_id,
            cargo_name, cargo_weight_kg, estimated_price, estimated_distance_km,
            status, claimed_at, picking_at, transit_at, arrived_at, completed_at, notes
        )
        VALUES (
            v_order_id, 1, v_driver_id, v_vehicle_id,
            'Showroom Cabinets', 180.0, 220000, 22.0,
            'completed',
            NOW() - INTERVAL '30 hours',
            NOW() - INTERVAL '29 hours',
            NOW() - INTERVAL '27 hours',
            NOW() - INTERVAL '25 hours',
            NOW() - INTERVAL '24 hours',
            'Driver completed shipment and submitted actual km for receipt request'
        )
        RETURNING id INTO v_shipment_id;
    ELSE
        SELECT id INTO v_shipment_id
        FROM order_shipments
        WHERE order_id = v_order_id AND shipment_index = 1
        LIMIT 1;

        UPDATE order_shipments
        SET owner_driver_id = v_driver_id,
            vehicle_id = v_vehicle_id,
            cargo_name = 'Showroom Cabinets',
            cargo_weight_kg = 180.0,
            estimated_price = 220000,
            estimated_distance_km = 22.0,
            status = 'completed',
            notes = 'Driver completed shipment and submitted actual km for receipt request'
        WHERE id = v_shipment_id;
    END IF;

    INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone, completed_at)
    SELECT v_shipment_id, 1, 'pickup', '12 Nguyen Van Linh, District 7', 'Warehouse Team', '0901010101', NOW() - INTERVAL '26 hours'
    WHERE NOT EXISTS (
        SELECT 1 FROM trip_stops WHERE shipment_id = v_shipment_id AND stop_index = 1
    );

    INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone, arrived_at, completed_at)
    SELECT v_shipment_id, 2, 'delivery', '88 Le Thanh Ton, District 1', 'Showroom Admin', '0902020202',
           NOW() - INTERVAL '25 hours', NOW() - INTERVAL '24 hours'
    WHERE NOT EXISTS (
        SELECT 1 FROM trip_stops WHERE shipment_id = v_shipment_id AND stop_index = 2
    );

    INSERT INTO shipment_assignments (shipment_id, driver_id, vehicle_id, assignment_type, assigned_by, assigned_at, accepted_at, completed_at)
    SELECT v_shipment_id, v_driver_id, v_vehicle_id, 'coordinator_assign', v_coordinator_id,
           NOW() - INTERVAL '30 hours', NOW() - INTERVAL '30 hours', NOW() - INTERVAL '24 hours'
    WHERE NOT EXISTS (
        SELECT 1 FROM shipment_assignments WHERE shipment_id = v_shipment_id AND driver_id = v_driver_id
    );

    INSERT INTO delivery_proofs (shipment_id, captured_by, file_url, is_realtime, captured_at)
    SELECT v_shipment_id, v_driver_id, 'https://res.cloudinary.com/demo/image/upload/receipt-pending-proof.jpg', TRUE, NOW() - INTERVAL '24 hours'
    WHERE NOT EXISTS (
        SELECT 1 FROM delivery_proofs WHERE shipment_id = v_shipment_id
    );

    UPDATE order_shipments
    SET actual_distance_km = 23.7,
        updated_at = NOW()
    WHERE id = v_shipment_id;

    INSERT INTO order_receipt_requests (requesting_shipment_id, order_id, driver_id, status, requested_at)
    SELECT v_shipment_id, v_order_id, v_driver_id, 'pending', NOW() - INTERVAL '90 minutes'
    WHERE NOT EXISTS (
        SELECT 1 FROM order_receipt_requests WHERE order_id = v_order_id
    );

    INSERT INTO expenses (shipment_id, vehicle_id, created_by, updated_by, expense_type, amount, description, expense_date)
    SELECT v_shipment_id, v_vehicle_id, v_coordinator_id, v_coordinator_id, 'toll', 45000,
           'Seeded toll cost for pending receipt review', CURRENT_DATE - 1
    WHERE NOT EXISTS (
        SELECT 1 FROM expenses
        WHERE shipment_id = v_shipment_id AND description = 'Seeded toll cost for pending receipt review'
    );

    INSERT INTO expenses (shipment_id, vehicle_id, created_by, updated_by, expense_type, amount, description, expense_date)
    SELECT v_shipment_id, v_vehicle_id, v_coordinator_id, v_coordinator_id, 'parking', 20000,
           'Seeded parking cost for pending receipt review', CURRENT_DATE - 1
    WHERE NOT EXISTS (
        SELECT 1 FROM expenses
        WHERE shipment_id = v_shipment_id AND description = 'Seeded parking cost for pending receipt review'
    );
END $$;

-- =============================================================================
-- SECTION 16B: RECEIPT REQUEST APPROVED DEMO (coordinator da publish)
-- =============================================================================
DO $$
DECLARE
    v_coordinator_id    INT;
    v_driver_id         INT;
    v_customer_id       INT;
    v_vehicle_id        INT;
    v_vehicle_group_id  INT;
    v_price_per_km      NUMERIC(12,2);
    v_estimated_km      NUMERIC(10,2) := 52.0;
    v_actual_km         NUMERIC(10,2) := 54.2;
    v_actual_income     NUMERIC(12,2);
    v_order_id          INT;
    v_shipment_id       INT;
    v_request_id        INT;
    v_receipt_id        INT;
BEGIN
    SELECT p.id INTO v_coordinator_id
    FROM profiles p JOIN accounts a ON a.id = p.id
    WHERE a.email = 'ntck005@gmail.com';

    SELECT p.id INTO v_driver_id
    FROM profiles p JOIN accounts a ON a.id = p.id
    WHERE a.email = 'driver4@example.com';

    SELECT v.id, v.vehicle_group_id, vg.price_per_km
    INTO v_vehicle_id, v_vehicle_group_id, v_price_per_km
    FROM vehicles v
    JOIN vehicle_groups vg ON vg.id = v.vehicle_group_id
    WHERE v.plate_number = '51-F44444';

    SELECT c.id INTO v_customer_id
    FROM customers c
    WHERE c.phone = '0987654324';

    v_actual_income := v_actual_km * v_price_per_km;

    IF NOT EXISTS (
        SELECT 1 FROM orders WHERE cargo_name = 'Receipt Approved Demo: Construction AC Units'
    ) THEN
        INSERT INTO orders (
            customer_id, created_by, cargo_name, cargo_weight_kg,
            total_estimated_price, total_actual_price, payment_type, vehicle_group_id,
            derived_status, notes
        )
        VALUES (
            v_customer_id, v_coordinator_id, 'Receipt Approved Demo: Construction AC Units', 320.0,
            v_estimated_km * v_price_per_km, v_actual_income, 'bank_transfer', v_vehicle_group_id,
            'completed', 'Coordinator already published receipt based on driver actual km'
        )
        RETURNING id INTO v_order_id;
    ELSE
        SELECT id INTO v_order_id
        FROM orders
        WHERE cargo_name = 'Receipt Approved Demo: Construction AC Units'
        LIMIT 1;

        UPDATE orders
        SET total_estimated_price = v_estimated_km * v_price_per_km,
            total_actual_price = v_actual_income,
            vehicle_group_id = v_vehicle_group_id,
            payment_type = 'bank_transfer',
            derived_status = 'completed',
            notes = 'Coordinator already published receipt based on driver actual km'
        WHERE id = v_order_id;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM order_shipments WHERE order_id = v_order_id AND shipment_index = 1
    ) THEN
        INSERT INTO order_shipments (
            order_id, shipment_index, owner_driver_id, vehicle_id,
            cargo_name, cargo_weight_kg, estimated_price, estimated_distance_km,
            actual_distance_km, actual_price, status,
            claimed_at, picking_at, transit_at, arrived_at, completed_at, notes
        )
        VALUES (
            v_order_id, 1, v_driver_id, v_vehicle_id,
            'Construction AC Units', 320.0, v_estimated_km * v_price_per_km, v_estimated_km,
            v_actual_km, v_actual_income, 'completed',
            NOW() - INTERVAL '18 hours',
            NOW() - INTERVAL '17 hours',
            NOW() - INTERVAL '15 hours',
            NOW() - INTERVAL '13 hours',
            NOW() - INTERVAL '12 hours',
            'Approved receipt demo with actual distance and saved actual income'
        )
        RETURNING id INTO v_shipment_id;
    ELSE
        SELECT id INTO v_shipment_id
        FROM order_shipments
        WHERE order_id = v_order_id AND shipment_index = 1
        LIMIT 1;

        UPDATE order_shipments
        SET owner_driver_id = v_driver_id,
            vehicle_id = v_vehicle_id,
            cargo_name = 'Construction AC Units',
            cargo_weight_kg = 320.0,
            estimated_price = v_estimated_km * v_price_per_km,
            estimated_distance_km = v_estimated_km,
            actual_distance_km = v_actual_km,
            actual_price = v_actual_income,
            status = 'completed',
            notes = 'Approved receipt demo with actual distance and saved actual income'
        WHERE id = v_shipment_id;
    END IF;

    INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone, completed_at)
    SELECT v_shipment_id, 1, 'pickup', '05 Quang Trung, Go Vap', 'Site Warehouse', '0903030303', NOW() - INTERVAL '14 hours'
    WHERE NOT EXISTS (
        SELECT 1 FROM trip_stops WHERE shipment_id = v_shipment_id AND stop_index = 1
    );

    INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone, arrived_at, completed_at)
    SELECT v_shipment_id, 2, 'delivery', '250 Dien Bien Phu, Binh Thanh', 'Project Supervisor', '0904040404',
           NOW() - INTERVAL '13 hours', NOW() - INTERVAL '12 hours'
    WHERE NOT EXISTS (
        SELECT 1 FROM trip_stops WHERE shipment_id = v_shipment_id AND stop_index = 2
    );

    INSERT INTO shipment_assignments (shipment_id, driver_id, vehicle_id, assignment_type, assigned_by, assigned_at, accepted_at, completed_at)
    SELECT v_shipment_id, v_driver_id, v_vehicle_id, 'coordinator_assign', v_coordinator_id,
           NOW() - INTERVAL '18 hours', NOW() - INTERVAL '18 hours', NOW() - INTERVAL '12 hours'
    WHERE NOT EXISTS (
        SELECT 1 FROM shipment_assignments WHERE shipment_id = v_shipment_id AND driver_id = v_driver_id
    );

    INSERT INTO delivery_proofs (shipment_id, captured_by, file_url, is_realtime, captured_at)
    SELECT v_shipment_id, v_driver_id, 'https://res.cloudinary.com/demo/image/upload/receipt-approved-proof.jpg', TRUE, NOW() - INTERVAL '12 hours'
    WHERE NOT EXISTS (
        SELECT 1 FROM delivery_proofs WHERE shipment_id = v_shipment_id
    );

    SELECT id INTO v_request_id
    FROM order_receipt_requests
    WHERE order_id = v_order_id
    LIMIT 1;

    IF v_request_id IS NULL THEN
        INSERT INTO order_receipt_requests (
            requesting_shipment_id, order_id, driver_id, status, requested_at,
            processed_by, processed_at, coordinator_notes
        )
        VALUES (
            v_shipment_id, v_order_id, v_driver_id, 'approved', NOW() - INTERVAL '11 hours',
            v_coordinator_id, NOW() - INTERVAL '10 hours',
            'Published by coordinator after checking actual km against vehicle group pricing'
        )
        RETURNING id INTO v_request_id;
    ELSE
        UPDATE order_receipt_requests
        SET driver_id = v_driver_id,
            status = 'approved',
            processed_by = v_coordinator_id,
            processed_at = NOW() - INTERVAL '10 hours',
            coordinator_notes = 'Published by coordinator after checking actual km against vehicle group pricing'
        WHERE id = v_request_id;
    END IF;

    SELECT id INTO v_receipt_id
    FROM shipment_receipts
    WHERE order_receipt_request_id = v_request_id
    LIMIT 1;

    IF v_receipt_id IS NULL THEN
        INSERT INTO shipment_receipts (
            shipment_id, payment_type, amount, collected_by, collected_at,
            notes, order_receipt_request_id, created_at, created_by
        )
        VALUES (
            v_shipment_id, 'bank_transfer', v_actual_income, NULL, NOW() - INTERVAL '10 hours',
            'Seeded approved receipt using actual km from driver request', v_request_id, NOW() - INTERVAL '10 hours', v_coordinator_id
        )
        RETURNING id INTO v_receipt_id;
    ELSE
        UPDATE shipment_receipts
        SET shipment_id = v_shipment_id,
            payment_type = 'bank_transfer',
            amount = v_actual_income,
            collected_by = NULL,
            collected_at = NOW() - INTERVAL '10 hours',
            notes = 'Seeded approved receipt using actual km from driver request',
            created_by = v_coordinator_id
        WHERE id = v_receipt_id;
    END IF;

    INSERT INTO expenses (shipment_id, vehicle_id, created_by, updated_by, expense_type, amount, description, expense_date)
    SELECT v_shipment_id, v_vehicle_id, v_coordinator_id, v_coordinator_id, 'fuel', 180000,
           'Seeded fuel expense for approved receipt demo', CURRENT_DATE
    WHERE NOT EXISTS (
        SELECT 1 FROM expenses
        WHERE shipment_id = v_shipment_id AND description = 'Seeded fuel expense for approved receipt demo'
    );

    INSERT INTO expenses (shipment_id, vehicle_id, created_by, updated_by, expense_type, amount, description, expense_date)
    SELECT v_shipment_id, v_vehicle_id, v_coordinator_id, v_coordinator_id, 'toll', 65000,
           'Seeded toll expense for approved receipt demo', CURRENT_DATE
    WHERE NOT EXISTS (
        SELECT 1 FROM expenses
        WHERE shipment_id = v_shipment_id AND description = 'Seeded toll expense for approved receipt demo'
    );

    UPDATE orders
    SET total_actual_price = (
            SELECT COALESCE(SUM(COALESCE(os.actual_price, 0)), 0)
            FROM order_shipments os
            WHERE os.order_id = v_order_id
        ),
        updated_at = NOW()
    WHERE id = v_order_id;
END $$;

-- =============================================================================
-- SECTION 17: TEST SCENARIO — Multi-Trip Order (3 chuyến cùng đơn)
-- Driver tự claim từng chuyến riêng lẻ
-- =============================================================================

INSERT INTO orders (customer_id, created_by, cargo_name, cargo_weight_kg,
                    total_estimated_price, payment_type, vehicle_group_id, derived_status, notes)
SELECT c.id, p.id, 'Multi-Trip: Hàng điện tử 3 chuyến', 150.0, 2100000, 'bank_transfer',
       (SELECT id FROM vehicle_groups ORDER BY id ASC LIMIT 1), 'open', '3 chuyến giao cho 3 điểm khác nhau'
FROM customers c, profiles p
JOIN accounts a ON a.id = p.id
WHERE c.phone = '0987654322'
  AND a.email = 'ntck005@gmail.com'
  AND NOT EXISTS (SELECT 1 FROM orders WHERE cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến')
LIMIT 1;

-- Trip 1 / 3
INSERT INTO order_shipments (order_id, shipment_index, cargo_name, cargo_weight_kg, estimated_price, status)
SELECT o.id, 1, 'Laptop Dell', 50.0, 700000, 'available'
FROM orders o WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến'
  AND NOT EXISTS (SELECT 1 FROM order_shipments os WHERE os.order_id = o.id AND os.shipment_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone)
SELECT os.id, 1, 'pickup', 'Kho FPT - KCN Tân Thuận, Q.7', 'Ms. Lan', '0903333333'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone)
SELECT os.id, 2, 'delivery', '100 Nguyễn Thị Minh Khai, Q.1', 'Mr. Bình', '0904444444'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 2);

-- Trip 2 / 3
INSERT INTO order_shipments (order_id, shipment_index, cargo_name, cargo_weight_kg, estimated_price, status)
SELECT o.id, 2, 'Màn hình Samsung', 60.0, 700000, 'available'
FROM orders o WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến'
  AND NOT EXISTS (SELECT 1 FROM order_shipments os WHERE os.order_id = o.id AND os.shipment_index = 2);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone)
SELECT os.id, 1, 'pickup', 'Kho FPT - KCN Tân Thuận, Q.7', 'Ms. Lan', '0903333333'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến' AND os.shipment_index = 2
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone)
SELECT os.id, 2, 'delivery', '200 Lý Tự Trọng, Q.1', 'Ms. Hương', '0905555555'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến' AND os.shipment_index = 2
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 2);

-- Trip 3 / 3
INSERT INTO order_shipments (order_id, shipment_index, cargo_name, cargo_weight_kg, estimated_price, status)
SELECT o.id, 3, 'Server rack', 40.0, 700000, 'available'
FROM orders o WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến'
  AND NOT EXISTS (SELECT 1 FROM order_shipments os WHERE os.order_id = o.id AND os.shipment_index = 3);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone)
SELECT os.id, 1, 'pickup', 'Kho FPT - KCN Tân Thuận, Q.7', 'Ms. Lan', '0903333333'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến' AND os.shipment_index = 3
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone)
SELECT os.id, 2, 'delivery', '300 Đinh Tiên Hoàng, Bình Thạnh', 'Mr. Sơn', '0906666666'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến' AND os.shipment_index = 3
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 2);

-- =============================================================================
-- SECTION 18: TEST SCENARIO — Shipment ARRIVED (chờ driver upload proof)
-- =============================================================================

INSERT INTO orders (customer_id, created_by, cargo_name, cargo_weight_kg,
                    total_estimated_price, payment_type, vehicle_group_id, derived_status, notes)
SELECT c.id, p.id, 'Arrived Test: Giao ngay hôm nay', 80.0, 650000, 'cash',
       (SELECT id FROM vehicle_groups ORDER BY id ASC LIMIT 1), 'open', 'Driver đã đến điểm giao, chờ xác nhận'
FROM customers c, profiles p
JOIN accounts a ON a.id = p.id
WHERE c.phone = '0987654321'
  AND a.email = 'ntck005@gmail.com'
  AND NOT EXISTS (SELECT 1 FROM orders WHERE cargo_name = 'Arrived Test: Giao ngay hôm nay')
LIMIT 1;

INSERT INTO order_shipments (order_id, shipment_index, owner_driver_id, vehicle_id,
                              cargo_name, cargo_weight_kg, estimated_price,
                              status, claimed_at, picking_at, transit_at, arrived_at)
SELECT o.id, 1, drv.id, v.id,
       'Đồ gia dụng', 80.0, 650000,
       'arrived',
       NOW() - INTERVAL '4 hours',
       NOW() - INTERVAL '3 hours',
       NOW() - INTERVAL '2 hours',
       NOW() - INTERVAL '10 minutes'
FROM orders o
JOIN accounts a ON a.email = 'driver1@example.com'
JOIN profiles drv ON drv.id = a.id
JOIN vehicles v ON v.plate_number = '51-A12345'
WHERE o.cargo_name = 'Arrived Test: Giao ngay hôm nay'
  AND NOT EXISTS (SELECT 1 FROM order_shipments os WHERE os.order_id = o.id AND os.shipment_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone, arrived_at, completed_at)
SELECT os.id, 1, 'pickup', '789 Cách Mạng Tháng 8, Q.3', 'Chị Mai', '0907777777',
       NOW() - INTERVAL '3 hours', NOW() - INTERVAL '2 hours'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Arrived Test: Giao ngay hôm nay' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone, arrived_at)
SELECT os.id, 2, 'delivery', '50 Hoàng Diệu, Q.4', 'Anh Khoa', '0908888888',
       NOW() - INTERVAL '10 minutes'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Arrived Test: Giao ngay hôm nay' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 2);

INSERT INTO shipment_assignments (shipment_id, driver_id, vehicle_id, assignment_type, assigned_at, accepted_at)
SELECT os.id, drv.id, v.id, 'self_claim', NOW() - INTERVAL '4 hours', NOW() - INTERVAL '4 hours'
FROM order_shipments os
JOIN orders o ON o.id = os.order_id
JOIN accounts a ON a.email = 'driver1@example.com'
JOIN profiles drv ON drv.id = a.id
JOIN vehicles v ON v.plate_number = '51-A12345'
WHERE o.cargo_name = 'Arrived Test: Giao ngay hôm nay' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM shipment_assignments sa WHERE sa.shipment_id = os.id AND sa.driver_id = drv.id);

-- =============================================================================
-- SECTION 19: TEST SCENARIO — Shipment FAILED (driver2, test hoàn hàng)
-- =============================================================================

INSERT INTO orders (customer_id, created_by, cargo_name, cargo_weight_kg,
                    total_estimated_price, payment_type, vehicle_group_id, derived_status, notes)
SELECT c.id, p.id, 'Failed Test: Khách từ chối nhận', 120.0, 500000, 'cash',
       (SELECT id FROM vehicle_groups ORDER BY id ASC LIMIT 1), 'open', 'Khách báo bận, không ra nhận hàng'
FROM customers c, profiles p
JOIN accounts a ON a.id = p.id
WHERE c.phone = '0987654324'
  AND a.email = 'ntck005@gmail.com'
  AND NOT EXISTS (SELECT 1 FROM orders WHERE cargo_name = 'Failed Test: Khách từ chối nhận')
LIMIT 1;

INSERT INTO order_shipments (order_id, shipment_index, owner_driver_id, vehicle_id,
                              cargo_name, cargo_weight_kg, estimated_price,
                              status, cancel_reason,
                              claimed_at, picking_at, transit_at, arrived_at, failed_at)
SELECT o.id, 1, drv2.id, v2.id,
       'Thực phẩm đông lạnh', 120.0, 500000,
       'failed', 'Khách từ chối nhận hàng, không liên lạc được',
       NOW() - INTERVAL '6 hours',
       NOW() - INTERVAL '5 hours',
       NOW() - INTERVAL '4 hours',
       NOW() - INTERVAL '1 hour',
       NOW() - INTERVAL '30 minutes'
FROM orders o
JOIN accounts a ON a.email = 'driver2@example.com'
JOIN profiles drv2 ON drv2.id = a.id
JOIN vehicles v2 ON v2.plate_number = '51-E33333'
WHERE o.cargo_name = 'Failed Test: Khách từ chối nhận'
  AND NOT EXISTS (SELECT 1 FROM order_shipments os WHERE os.order_id = o.id AND os.shipment_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, arrived_at, completed_at)
SELECT os.id, 1, 'pickup', 'Kho lạnh - 88 Bến Vân Đồn, Q.4',
       NOW() - INTERVAL '5 hours', NOW() - INTERVAL '4 hours'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Failed Test: Khách từ chối nhận' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, arrived_at)
SELECT os.id, 2, 'delivery', '22 Nguyễn Văn Cừ, Q.5', NOW() - INTERVAL '1 hour'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Failed Test: Khách từ chối nhận' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 2);

-- =============================================================================
-- SECTION 20: TEST SCENARIO — Driver Debt (driver1 đã thu tiền mặt)
-- Test: GET /api/debts/me, POST /api/debts/:id/remit
-- =============================================================================
DO $$
DECLARE
    v_shipment_id INT;
    v_driver_id   INT;
    v_order_id    INT;
    v_payment_id  INT;
    v_vehicle_id  INT;
    v_group_id    INT;
    v_customer_id INT;
    v_coord_id    INT;
BEGIN
    SELECT p.id INTO v_driver_id
    FROM profiles p JOIN accounts a ON a.id = p.id WHERE a.email = 'driver1@example.com';

    SELECT p.id INTO v_coord_id
    FROM profiles p JOIN accounts a ON a.id = p.id WHERE a.email = 'ntck005@gmail.com';

    SELECT id, vehicle_group_id INTO v_vehicle_id, v_group_id
    FROM vehicles
    WHERE plate_number = '51-A12345';

    SELECT id INTO v_customer_id
    FROM customers
    WHERE phone = '0987654321';

    IF NOT EXISTS (
        SELECT 1 FROM orders WHERE cargo_name = 'Driver Debt Demo: Cash Collected Office Supplies'
    ) THEN
        INSERT INTO orders (
            customer_id, created_by, cargo_name, cargo_weight_kg,
            total_estimated_price, total_actual_price, payment_type,
            vehicle_group_id, derived_status, notes
        )
        VALUES (
            v_customer_id, v_coord_id, 'Driver Debt Demo: Cash Collected Office Supplies', 95.0,
            1500000, 1500000, 'cash', v_group_id, 'completed',
            'Dedicated cash-collected demo for driver debt and remittance flow'
        )
        RETURNING id INTO v_order_id;
    ELSE
        SELECT id INTO v_order_id
        FROM orders
        WHERE cargo_name = 'Driver Debt Demo: Cash Collected Office Supplies'
        LIMIT 1;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM order_shipments WHERE order_id = v_order_id AND shipment_index = 1
    ) THEN
        INSERT INTO order_shipments (
            order_id, shipment_index, owner_driver_id, vehicle_id,
            cargo_name, cargo_weight_kg, estimated_price, estimated_distance_km,
            actual_distance_km, actual_price, status,
            claimed_at, picking_at, transit_at, arrived_at, completed_at, notes
        )
        VALUES (
            v_order_id, 1, v_driver_id, v_vehicle_id,
            'Office Supplies', 95.0, 1500000, 150.0,
            150.0, 1500000, 'completed',
            NOW() - INTERVAL '3 days',
            NOW() - INTERVAL '3 days' + INTERVAL '1 hour',
            NOW() - INTERVAL '3 days' + INTERVAL '3 hours',
            NOW() - INTERVAL '3 days' + INTERVAL '5 hours',
            NOW() - INTERVAL '2 days',
            'Dedicated shipment for cash collected and driver debt settlement testing'
        )
        RETURNING id INTO v_shipment_id;
    ELSE
        SELECT id INTO v_shipment_id
        FROM order_shipments
        WHERE order_id = v_order_id AND shipment_index = 1
        LIMIT 1;
    END IF;

    IF v_shipment_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM shipment_receipts WHERE shipment_id = v_shipment_id
    ) THEN
        INSERT INTO shipment_receipts (shipment_id, payment_type, amount, collected_by, notes, collected_at)
        VALUES (v_shipment_id, 'cash_collected', 1500000, v_driver_id,
                'Khách thanh toán tiền mặt khi nhận hàng', NOW() - INTERVAL '1 day')
        RETURNING id INTO v_payment_id;

        INSERT INTO payment_receipts (payment_id, file_url, uploaded_at)
        VALUES (v_payment_id, 'https://res.cloudinary.com/demo/image/upload/sample.jpg', NOW() - INTERVAL '1 day');

        INSERT INTO debts (debt_type, driver_id, shipment_id, order_id, total_amount, paid_amount, status, notes)
        VALUES ('driver', v_driver_id, v_shipment_id, v_order_id, 1500000, 500000, 'partial',
                'Khách thanh toán tiền mặt — driver đang cầm tiền');

        -- Lần nộp 1: đã được kế toán xác nhận
        INSERT INTO debt_payments (debt_id, amount, payment_method, status, receipt_url,
                                   confirmed_at, created_by, notes, paid_at)
        SELECT d.id, 500000, 'cash', 'confirmed',
               'https://res.cloudinary.com/demo/image/upload/sample.jpg',
               NOW() - INTERVAL '10 hours', v_driver_id, 'Nộp tiền mặt tại văn phòng', NOW() - INTERVAL '12 hours'
        FROM debts d WHERE d.driver_id = v_driver_id AND d.total_amount = 1500000;

        -- Lần nộp 2: đang chờ kế toán xác nhận
        INSERT INTO debt_payments (debt_id, amount, payment_method, status, receipt_url,
                                   created_by, notes, paid_at)
        SELECT d.id, 700000, 'bank_transfer', 'pending',
               'https://res.cloudinary.com/demo/image/upload/sample2.jpg',
               v_driver_id, 'Chuyển khoản 700k còn lại', NOW() - INTERVAL '1 hour'
        FROM debts d WHERE d.driver_id = v_driver_id AND d.total_amount = 1500000;

        -- Công nợ thứ 2 (chưa nộp)
        INSERT INTO debts (debt_type, driver_id, order_id, total_amount, paid_amount, status, notes)
        VALUES ('driver', v_driver_id, v_order_id, 800000, 0, 'unpaid',
                'Thu hộ chuyến thứ 2, chưa nộp về công ty');
    END IF;
END $$;

-- =============================================================================
-- SECTION 21: TEST SCENARIO — Payroll tháng 5/2026 đã duyệt
-- Test: GET /api/payroll/me
-- =============================================================================
INSERT INTO payrolls (
    driver_id, payroll_month, payroll_year,
    base_salary, months_of_service,
    total_revenue, revenue_share_pct, revenue_bonus,
    kpi_bonus, top_driver_bonus, other_bonus,
    insurance_employee, driver_debt_deduction, advance_deduction, other_deduction,
    status
)
SELECT p.id, 5, 2026,
       9000000, 40,
       15000000, 15.00, 2250000,
       500000, 0, 200000,
       900000, 500000, 0, 0,
       'approved'
FROM profiles p JOIN accounts a ON a.id = p.id
WHERE a.email = 'driver1@example.com'
  AND NOT EXISTS (
      SELECT 1 FROM payrolls pw WHERE pw.driver_id = p.id AND pw.payroll_month = 5 AND pw.payroll_year = 2026
  );

-- =============================================================================
-- SECTION 22: TEST SCENARIO — Salary Advance pending
-- Test: GET /api/payroll/advance
-- =============================================================================
INSERT INTO salary_advances (driver_id, amount, reason, request_month, request_year, status)
SELECT p.id, 2000000, 'Cần tiền đóng học phí cho con', 6, 2026, 'pending'
FROM profiles p JOIN accounts a ON a.id = p.id
WHERE a.email = 'driver1@example.com'
  AND NOT EXISTS (
      SELECT 1 FROM salary_advances sa
      WHERE sa.driver_id = p.id AND sa.request_month = 6 AND sa.request_year = 2026
        AND sa.status IN ('pending', 'approved')
  );

-- =============================================================================
-- SECTION 23: TEST SCENARIO — KPI tháng 4-6/2026
-- Test: GET /api/kpi/me, GET /api/kpi/leaderboard
-- =============================================================================
DO $$
DECLARE
    v_driver1_id   INT;
    v_driver2_id   INT;
    v_group_small  INT;
BEGIN
    SELECT p.id INTO v_driver1_id FROM profiles p JOIN accounts a ON a.id = p.id WHERE a.email = 'driver1@example.com';
    SELECT p.id INTO v_driver2_id FROM profiles p JOIN accounts a ON a.id = p.id WHERE a.email = 'driver2@example.com';
    SELECT id  INTO v_group_small  FROM vehicle_groups ORDER BY id ASC LIMIT 1;

    -- Driver 1 — tháng 6/2026 (tháng hiện tại)
    INSERT INTO kpi_records (driver_id, vehicle_group_id, month, year,
                              completed_shipments, total_revenue, incident_count)
    VALUES (v_driver1_id, v_group_small, 6, 2026, 18, 12600000, 1)
    ON CONFLICT (driver_id, month, year) DO UPDATE SET
        completed_shipments = EXCLUDED.completed_shipments,
        total_revenue       = EXCLUDED.total_revenue,
        incident_count      = EXCLUDED.incident_count;

    -- Driver 1 — tháng 5/2026
    INSERT INTO kpi_records (driver_id, vehicle_group_id, month, year,
                              completed_shipments, total_revenue, incident_count)
    VALUES (v_driver1_id, v_group_small, 5, 2026, 22, 15400000, 0)
    ON CONFLICT (driver_id, month, year) DO UPDATE SET
        completed_shipments = EXCLUDED.completed_shipments,
        total_revenue       = EXCLUDED.total_revenue,
        incident_count      = EXCLUDED.incident_count;

    -- Driver 1 — tháng 4/2026
    INSERT INTO kpi_records (driver_id, vehicle_group_id, month, year,
                              completed_shipments, total_revenue, incident_count)
    VALUES (v_driver1_id, v_group_small, 4, 2026, 19, 13300000, 0)
    ON CONFLICT (driver_id, month, year) DO UPDATE SET
        completed_shipments = EXCLUDED.completed_shipments,
        total_revenue       = EXCLUDED.total_revenue,
        incident_count      = EXCLUDED.incident_count;

    -- Driver 2 — tháng 6/2026 (leaderboard)
    INSERT INTO kpi_records (driver_id, vehicle_group_id, month, year,
                              completed_shipments, total_revenue, incident_count)
    VALUES (v_driver2_id, v_group_small, 6, 2026, 25, 17500000, 0)
    ON CONFLICT (driver_id, month, year) DO UPDATE SET
        completed_shipments = EXCLUDED.completed_shipments,
        total_revenue       = EXCLUDED.total_revenue,
        incident_count      = EXCLUDED.incident_count;

    -- Driver 2 — tháng 5/2026
    INSERT INTO kpi_records (driver_id, vehicle_group_id, month, year,
                              completed_shipments, total_revenue, incident_count)
    VALUES (v_driver2_id, v_group_small, 5, 2026, 20, 14000000, 1)
    ON CONFLICT (driver_id, month, year) DO UPDATE SET
        completed_shipments = EXCLUDED.completed_shipments,
        total_revenue       = EXCLUDED.total_revenue,
        incident_count      = EXCLUDED.incident_count;
END $$;

-- =============================================================================
-- SECTION 24: TEST SCENARIO — Incident mở (driver2, từ chối nhận hàng)
-- Test: GET /api/incidents/my
-- =============================================================================
DO $$
DECLARE
    v_shipment_id INT;
    v_driver2_id  INT;
BEGIN
    SELECT p.id INTO v_driver2_id
    FROM profiles p JOIN accounts a ON a.id = p.id WHERE a.email = 'driver2@example.com';

    SELECT os.id INTO v_shipment_id
    FROM order_shipments os JOIN orders o ON o.id = os.order_id
    WHERE o.cargo_name = 'Failed Test: Khách từ chối nhận' AND os.shipment_index = 1 LIMIT 1;

    IF v_shipment_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM incidents WHERE shipment_id = v_shipment_id
    ) THEN
        INSERT INTO incidents (shipment_id, vehicle_id, reported_by, incident_type, severity_level,
                               description, location, status, occurred_at)
        VALUES (v_shipment_id, NULL, v_driver2_id, 'customer_refusal', 'low',
                'Khách hàng không ra nhận hàng sau nhiều lần gọi điện. Đã chờ 30 phút tại điểm giao.',
                '22 Nguyễn Văn Cừ, Q.5, TP.HCM', 'open', NOW() - INTERVAL '30 minutes');
    END IF;
END $$;

-- =============================================================================
-- SECTION 25: TEST SCENARIO — Leave Requests tháng 4-6/2026
-- Test: GET /api/leave/me, GET /api/leave/summary
-- =============================================================================
DO $$
DECLARE
    v_driver_id INT;
BEGIN
    SELECT p.id INTO v_driver_id
    FROM profiles p JOIN accounts a ON a.id = p.id WHERE a.email = 'driver1@example.com';

    IF v_driver_id IS NOT NULL THEN
        INSERT INTO leave_requests (driver_id, leave_date, leave_type, reason, status)
        VALUES (v_driver_id, '2026-06-10', 'unpaid', 'Việc gia đình', 'approved')
        ON CONFLICT (driver_id, leave_date) DO NOTHING;

        INSERT INTO leave_requests (driver_id, leave_date, leave_type, reason, status)
        VALUES (v_driver_id, '2026-04-18', 'paid', 'Giỗ Tổ Hùng Vương', 'approved')
        ON CONFLICT (driver_id, leave_date) DO NOTHING;
    END IF;
END $$;

-- =============================================================================
-- SEED VALIDATION — Đếm số bản ghi sau khi seed
-- =============================================================================
SELECT '✓ Accounts'          AS entity, COUNT(*) AS count FROM accounts
UNION ALL SELECT '✓ Profiles',           COUNT(*) FROM profiles
UNION ALL SELECT '✓ Customers',          COUNT(*) FROM customers
UNION ALL SELECT '✓ Vehicle Groups',     COUNT(*) FROM vehicle_groups
UNION ALL SELECT '✓ Vehicles',           COUNT(*) FROM vehicles
UNION ALL SELECT '✓ Orders',             COUNT(*) FROM orders
UNION ALL SELECT '✓ Shipments',          COUNT(*) FROM order_shipments
UNION ALL SELECT '✓ Trip Stops',         COUNT(*) FROM trip_stops
UNION ALL SELECT '✓ Drivers',            COUNT(*) FROM drivers
UNION ALL SELECT '✓ KPI Records',        COUNT(*) FROM kpi_records
UNION ALL SELECT '✓ Payrolls',           COUNT(*) FROM payrolls
UNION ALL SELECT '✓ Salary Advances',    COUNT(*) FROM salary_advances
UNION ALL SELECT '✓ Debts (driver)',     COUNT(*) FROM debts WHERE debt_type = 'driver'
UNION ALL SELECT '✓ Incidents',          COUNT(*) FROM incidents
UNION ALL SELECT '✓ Leave Requests',     COUNT(*) FROM leave_requests
UNION ALL SELECT '✓ Receipt Requests',   COUNT(*) FROM order_receipt_requests
UNION ALL SELECT '✓ Shipment Receipts',  COUNT(*) FROM shipment_receipts
UNION ALL SELECT '✓ Expenses',           COUNT(*) FROM expenses
UNION ALL SELECT '✓ Delivery Proofs',    COUNT(*) FROM delivery_proofs
UNION ALL SELECT '✓ Maintenance',        COUNT(*) FROM maintenance_records;
