-- ============================================================================
-- TEST SEED — Driver Module Full Coverage
-- Chạy SAU khi đã chạy "DB script.sql" và "seed.sql"
-- Mục tiêu: data đủ để test toàn bộ flow driver
-- ============================================================================

-- ─── MIGRATION: xóa cột status khỏi debt_payments (không còn pending flow) ───
ALTER TABLE debt_payments DROP COLUMN IF EXISTS status;

-- ─── MIGRATION: tạo bảng bills nếu chưa có ────────────────────────
CREATE TABLE IF NOT EXISTS bills (
    id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    driver_id       INT NOT NULL REFERENCES profiles(id),
    shipment_id     INT REFERENCES order_shipments(id),
    amount          NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    payment_method  TEXT NOT NULL DEFAULT 'cash' CHECK (payment_method IN ('cash', 'bank_transfer')),
    status          TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'confirmed', 'rejected', 'converted')),
    notes           TEXT,
    receipt_url     TEXT,
    collected_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    confirmed_by    INT REFERENCES profiles(id),
    confirmed_at    TIMESTAMPTZ,
    reject_reason   TEXT,
    debt_id         INT REFERENCES debts(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── MIGRATION: tạo bảng leave_requests nếu chưa có ──────────────────────────
CREATE TABLE IF NOT EXISTS leave_requests (
    id          INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    driver_id   INT NOT NULL REFERENCES profiles(id),
    leave_date  DATE NOT NULL,
    leave_type  TEXT NOT NULL DEFAULT 'unpaid'
                    CHECK (leave_type IN ('paid', 'unpaid')),
    reason      TEXT,
    status      TEXT NOT NULL DEFAULT 'approved'
                    CHECK (status IN ('approved', 'rejected')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (driver_id, leave_date)
);

-- ─── DRIVER 2 (cùng nhóm xe Small Van, để test leaderboard / pool) ───────────

INSERT INTO accounts (email, password_hash, role_id, is_active)
SELECT 'driver2@example.com', crypt('driver123', gen_salt('bf')),
       (SELECT id FROM roles WHERE name = 'driver'), TRUE
WHERE NOT EXISTS (SELECT 1 FROM accounts WHERE email = 'driver2@example.com');

INSERT INTO profiles (id, full_name, phone, role_id)
SELECT a.id, 'Pham Driver 2', '0901234590',
       (SELECT id FROM roles WHERE name = 'driver')
FROM accounts a
WHERE a.email = 'driver2@example.com'
ON CONFLICT (id) DO NOTHING;

INSERT INTO vehicles (plate_number, vehicle_group_id, brand, model, load_capacity_kg, manufacture_year, status)
SELECT '51-E33333',
       (SELECT id FROM vehicle_groups WHERE price_per_km = 10000),
       'Kia', 'K200', 2000, 2023, 'available'
WHERE NOT EXISTS (SELECT 1 FROM vehicles WHERE plate_number = '51-E33333');

INSERT INTO drivers (profile_id, license_number, license_expiry_date, hire_date, revenue_share_percent)
SELECT p.id, 'DL654321', '2028-06-30', '2024-06-01', 15
FROM profiles p JOIN accounts a ON a.id = p.id
WHERE a.email = 'driver2@example.com'
ON CONFLICT (profile_id) DO NOTHING;

UPDATE vehicles SET assigned_driver_id = (
    SELECT p.id FROM profiles p JOIN accounts a ON a.id = p.id WHERE a.email = 'driver2@example.com'
) WHERE plate_number = '51-E33333' AND assigned_driver_id IS NULL;

UPDATE drivers SET vehicle_id = (SELECT id FROM vehicles WHERE plate_number = '51-E33333')
WHERE profile_id = (
    SELECT p.id FROM profiles p JOIN accounts a ON a.id = p.id WHERE a.email = 'driver2@example.com'
) AND vehicle_id IS NULL;

-- ─── SCENARIO 1: X2C — Shipment có 2 runs, đang AVAILABLE trong pool ─────────
-- Driver nào cũng nhận được (nhóm Small Van)

INSERT INTO orders (customer_id, created_by, cargo_name, cargo_weight_kg,
                    total_estimated_price, payment_type, derived_status, notes)
SELECT c.id, p.id, 'X2C Test: Thùng hàng xi măng', 1800.0, 800000,
       'cash', 'open', 'Chạy 2 lượt A→B, mỗi lượt 900kg'
FROM customers c, profiles p
JOIN accounts a ON a.id = p.id
WHERE c.phone = '0987654323'
  AND a.email = 'ntck005@gmail.com'
  AND NOT EXISTS (SELECT 1 FROM orders WHERE cargo_name = 'X2C Test: Thùng hàng xi măng')
LIMIT 1;

INSERT INTO order_shipments (order_id, shipment_index, vehicle_group_id,
                              cargo_name, cargo_weight_kg, estimated_price, status)
SELECT o.id, 1,
       (SELECT id FROM vehicle_groups WHERE price_per_km = 10000),
       'Xi măng PCB40', 1800.0, 800000, 'available'
FROM orders o
WHERE o.cargo_name = 'X2C Test: Thùng hàng xi măng'
  AND NOT EXISTS (
      SELECT 1 FROM order_shipments os WHERE os.order_id = o.id AND os.shipment_index = 1
  );

-- Stops cho X2C shipment (cùng tuyến A→B, driver chạy 2 lần)
INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone, notes)
SELECT os.id, 1, 'pickup', 'Kho xi măng - 45 Trường Chinh, Q.Tân Bình', 'Anh Tuấn (thủ kho)', '0901111111', 'Lấy 900kg/lượt, cân tại kho'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'X2C Test: Thùng hàng xi măng' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone)
SELECT os.id, 2, 'delivery', 'Công trình 123 Lê Đức Thọ, Q.Gò Vấp', 'Anh Hùng (quản lý)', '0902222222'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'X2C Test: Thùng hàng xi măng' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 2);

-- trip_runs sẽ do coordinator tạo sau khi có UI. Chưa insert vào đây.

-- ─── SCENARIO 2: Multi-Trip Order — 3 trips cùng đơn, driver tự claim từng cái ─

INSERT INTO orders (customer_id, created_by, cargo_name, cargo_weight_kg,
                    total_estimated_price, payment_type, derived_status, notes)
SELECT c.id, p.id, 'Multi-Trip: Hàng điện tử 3 chuyến', 150.0, 2100000,
       'bank_transfer', 'open', '3 chuyến giao cho 3 điểm khác nhau'
FROM customers c, profiles p
JOIN accounts a ON a.id = p.id
WHERE c.phone = '0987654322'
  AND a.email = 'ntck005@gmail.com'
  AND NOT EXISTS (SELECT 1 FROM orders WHERE cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến')
LIMIT 1;

-- Trip 1 / 3 — available
INSERT INTO order_shipments (order_id, shipment_index, vehicle_group_id,
                              cargo_name, cargo_weight_kg, estimated_price, status)
SELECT o.id, 1, (SELECT id FROM vehicle_groups WHERE price_per_km = 10000),
       'Laptop Dell', 50.0, 700000, 'available'
FROM orders o WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến'
  AND NOT EXISTS (SELECT 1 FROM order_shipments os WHERE os.order_id = o.id AND os.shipment_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone)
SELECT os.id, 1, 'pickup', 'Kho FPT - KCN Tân Thuận, Q.7', 'Ms. Lan', '0903333333'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 1);
INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone)
SELECT os.id, 2, 'delivery', '100 Nguyễn Thị Minh Khai, Q.1', 'Mr. Bình', '0904444444'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 2);

-- Trip 2 / 3 — available
INSERT INTO order_shipments (order_id, shipment_index, vehicle_group_id,
                              cargo_name, cargo_weight_kg, estimated_price, status)
SELECT o.id, 2, (SELECT id FROM vehicle_groups WHERE price_per_km = 10000),
       'Màn hình Samsung', 60.0, 700000, 'available'
FROM orders o WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến'
  AND NOT EXISTS (SELECT 1 FROM order_shipments os WHERE os.order_id = o.id AND os.shipment_index = 2);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone)
SELECT os.id, 1, 'pickup', 'Kho FPT - KCN Tân Thuận, Q.7', 'Ms. Lan', '0903333333'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến' AND os.shipment_index = 2
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 1);
INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone)
SELECT os.id, 2, 'delivery', '200 Lý Tự Trọng, Q.1', 'Ms. Hương', '0905555555'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến' AND os.shipment_index = 2
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 2);

-- Trip 3 / 3 — available
INSERT INTO order_shipments (order_id, shipment_index, vehicle_group_id,
                              cargo_name, cargo_weight_kg, estimated_price, status)
SELECT o.id, 3, (SELECT id FROM vehicle_groups WHERE price_per_km = 10000),
       'Server rack', 40.0, 700000, 'available'
FROM orders o WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến'
  AND NOT EXISTS (SELECT 1 FROM order_shipments os WHERE os.order_id = o.id AND os.shipment_index = 3);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone)
SELECT os.id, 1, 'pickup', 'Kho FPT - KCN Tân Thuận, Q.7', 'Ms. Lan', '0903333333'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến' AND os.shipment_index = 3
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 1);
INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone)
SELECT os.id, 2, 'delivery', '300 Đinh Tiên Hoàng, Bình Thạnh', 'Mr. Sơn', '0906666666'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Multi-Trip: Hàng điện tử 3 chuyến' AND os.shipment_index = 3
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 2);

-- ─── SCENARIO 3: Shipment ARRIVED — driver1 đang chờ complete ────────────────
-- Test flow: POST /trips/:id/complete (upload proof)

INSERT INTO orders (customer_id, created_by, cargo_name, cargo_weight_kg,
                    total_estimated_price, payment_type, derived_status, notes)
SELECT c.id, p.id, 'Arrived Test: Giao ngay hôm nay', 80.0, 650000,
       'cash', 'open', 'Driver đã đến điểm giao, chờ xác nhận'
FROM customers c, profiles p
JOIN accounts a ON a.id = p.id
WHERE c.phone = '0987654321'
  AND a.email = 'ntck005@gmail.com'
  AND NOT EXISTS (SELECT 1 FROM orders WHERE cargo_name = 'Arrived Test: Giao ngay hôm nay')
LIMIT 1;

INSERT INTO order_shipments (order_id, shipment_index, vehicle_group_id,
                              owner_driver_id, vehicle_id,
                              cargo_name, cargo_weight_kg, estimated_price,
                              status, claimed_at, picking_at, loaded_at, transit_at, arrived_at)
SELECT o.id, 1,
       (SELECT id FROM vehicle_groups WHERE price_per_km = 10000),
       drv.id, v.id,
       'Đồ gia dụng', 80.0, 650000,
       'arrived',
       NOW() - INTERVAL '4 hours',
       NOW() - INTERVAL '3 hours',
       NOW() - INTERVAL '2 hours 30 minutes',
       NOW() - INTERVAL '2 hours',
       NOW() - INTERVAL '10 minutes'
FROM orders o
JOIN accounts a ON a.email = 'driver1@example.com'
JOIN profiles drv ON drv.id = a.id
JOIN vehicles v ON v.plate_number = '51-A12345'
WHERE o.cargo_name = 'Arrived Test: Giao ngay hôm nay'
  AND NOT EXISTS (SELECT 1 FROM order_shipments os WHERE os.order_id = o.id AND os.shipment_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone, arrived_at, completed_at)
SELECT os.id, 1, 'pickup', '789 Cách Mạng Tháng 8, Q.3', 'Chị Mai', '0907777777',
       NOW() - INTERVAL '3 hours', NOW() - INTERVAL '2 hours 30 minutes'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Arrived Test: Giao ngay hôm nay' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, contact_name, contact_phone, arrived_at)
SELECT os.id, 2, 'delivery', '50 Hoàng Diệu, Q.4', 'Anh Khoa', '0908888888',
       NOW() - INTERVAL '10 minutes'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Arrived Test: Giao ngay hôm nay' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 2);

-- shipment_assignments cho arrived shipment
INSERT INTO shipment_assignments (shipment_id, driver_id, vehicle_id, assignment_type, assigned_at, accepted_at)
SELECT os.id, drv.id, v.id, 'self_claim', NOW() - INTERVAL '4 hours', NOW() - INTERVAL '4 hours'
FROM order_shipments os
JOIN orders o ON o.id = os.order_id
JOIN accounts a ON a.email = 'driver1@example.com'
JOIN profiles drv ON drv.id = a.id
JOIN vehicles v ON v.plate_number = '51-A12345'
WHERE o.cargo_name = 'Arrived Test: Giao ngay hôm nay' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM shipment_assignments sa WHERE sa.shipment_id = os.id AND sa.driver_id = drv.id);

-- ─── SCENARIO 4: Shipment FAILED → RETURNING — test hoàn hàng ────────────────

INSERT INTO orders (customer_id, created_by, cargo_name, cargo_weight_kg,
                    total_estimated_price, payment_type, derived_status, notes)
SELECT c.id, p.id, 'Failed Test: Khách từ chối nhận', 120.0, 500000,
       'cash', 'open', 'Khách báo bận, không ra nhận hàng'
FROM customers c, profiles p
JOIN accounts a ON a.id = p.id
WHERE c.phone = '0987654324'
  AND a.email = 'ntck005@gmail.com'
  AND NOT EXISTS (SELECT 1 FROM orders WHERE cargo_name = 'Failed Test: Khách từ chối nhận')
LIMIT 1;

INSERT INTO order_shipments (order_id, shipment_index, vehicle_group_id,
                              owner_driver_id, vehicle_id,
                              cargo_name, cargo_weight_kg, estimated_price,
                              status, cancel_reason,
                              claimed_at, picking_at, loaded_at, transit_at, arrived_at, failed_at)
SELECT o.id, 1,
       (SELECT id FROM vehicle_groups WHERE price_per_km = 10000),
       drv2.id, v2.id,
       'Thực phẩm đông lạnh', 120.0, 500000,
       'failed', 'Khách từ chối nhận hàng, không liên lạc được',
       NOW() - INTERVAL '6 hours',
       NOW() - INTERVAL '5 hours',
       NOW() - INTERVAL '4 hours 30 minutes',
       NOW() - INTERVAL '4 hours',
       NOW() - INTERVAL '1 hour',
       NOW() - INTERVAL '30 minutes'
FROM orders o
JOIN accounts a ON a.email = 'driver2@example.com'
JOIN profiles drv2 ON drv2.id = a.id
JOIN vehicles v2 ON v2.plate_number = '51-E33333'
WHERE o.cargo_name = 'Failed Test: Khách từ chối nhận'
  AND NOT EXISTS (SELECT 1 FROM order_shipments os WHERE os.order_id = o.id AND os.shipment_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, arrived_at, completed_at)
SELECT os.id, 1, 'pickup', 'Kho lạnh - 88 Bến Vân Đồn, Q.4', NOW() - INTERVAL '5 hours', NOW() - INTERVAL '4 hours 30 minutes'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Failed Test: Khách từ chối nhận' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 1);

INSERT INTO trip_stops (shipment_id, stop_index, stop_type, address, arrived_at)
SELECT os.id, 2, 'delivery', '22 Nguyễn Văn Cừ, Q.5', NOW() - INTERVAL '1 hour'
FROM order_shipments os JOIN orders o ON o.id = os.order_id
WHERE o.cargo_name = 'Failed Test: Khách từ chối nhận' AND os.shipment_index = 1
  AND NOT EXISTS (SELECT 1 FROM trip_stops ts WHERE ts.shipment_id = os.id AND ts.stop_index = 2);

-- ─── SCENARIO 5: Driver Debt — driver1 đã thu tiền mặt của khách ─────────────
-- Test: GET /api/debts/me, POST /api/debts/:id/remit

DO $$
DECLARE
    v_completed_shipment_id INT;
    v_driver_id INT;
    v_order_id  INT;
    v_payment_id INT;
BEGIN
    SELECT p.id INTO v_driver_id FROM profiles p JOIN accounts a ON a.id = p.id WHERE a.email = 'driver1@example.com';
    SELECT os.id, os.order_id INTO v_completed_shipment_id, v_order_id
    FROM order_shipments os JOIN orders o ON o.id = os.order_id
    WHERE o.cargo_name = 'Furniture Set' AND os.status = 'completed' LIMIT 1;

    IF v_completed_shipment_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM shipment_payments WHERE shipment_id = v_completed_shipment_id
    ) THEN
        INSERT INTO shipment_payments (shipment_id, payment_type, amount, collected_by, notes, collected_at)
        VALUES (v_completed_shipment_id, 'cash_collected', 1500000, v_driver_id, 'Khách thanh toán tiền mặt khi nhận hàng', NOW() - INTERVAL '1 day')
        RETURNING id INTO v_payment_id;

        INSERT INTO payment_receipts (payment_id, file_url, uploaded_at)
        VALUES (v_payment_id, 'https://res.cloudinary.com/demo/image/upload/sample.jpg', NOW() - INTERVAL '1 day');

        INSERT INTO debts (debt_type, driver_id, shipment_id, order_id, total_amount, paid_amount, status, notes)
        VALUES ('driver', v_driver_id, v_completed_shipment_id, v_order_id, 1500000, 500000, 'partial',
                'Driver đã nộp 500k ngày hôm qua, còn 1M chưa nộp');

        -- Ghi nhận lần nộp tiền đầu tiên
        -- status='confirmed': kế toán đã xác nhận, khớp với paid_amount trên debts
        INSERT INTO debt_payments (debt_id, amount, payment_method, created_by, notes, paid_at)
        SELECT d.id, 500000, 'cash', v_driver_id, 'Kế toán ghi nhận nộp tiền mặt', NOW() - INTERVAL '12 hours'
        FROM debts d WHERE d.driver_id = v_driver_id AND d.total_amount = 1500000;

        -- Seed bills: 1 pending, 1 confirmed, 1 rejected
        INSERT INTO bills (driver_id, shipment_id, amount, payment_method, status, notes, collected_at)
        SELECT v_driver_id, os.id, 800000, 'cash', 'pending',
               'Thu tiền mặt từ khách — chờ kế toán xác nhận', NOW() - INTERVAL '2 hours'
        FROM order_shipments os WHERE os.owner_driver_id = v_driver_id LIMIT 1;

        INSERT INTO bills (driver_id, shipment_id, amount, payment_method, status, notes, collected_at, confirmed_at)
        SELECT v_driver_id, os.id, 1200000, 'bank_transfer', 'confirmed',
               'Khách chuyển khoản, đã nộp kế toán', NOW() - INTERVAL '3 days', NOW() - INTERVAL '2 days'
        FROM order_shipments os WHERE os.owner_driver_id = v_driver_id LIMIT 1;

        INSERT INTO bills (driver_id, shipment_id, amount, payment_method, status, notes, collected_at, reject_reason)
        SELECT v_driver_id, os.id, 500000, 'cash', 'rejected',
               'Ghi chú test', NOW() - INTERVAL '5 days', 'Số tiền không khớp với hóa đơn'
        FROM order_shipments os WHERE os.owner_driver_id = v_driver_id LIMIT 1;
    END IF;
END $$;

-- ─── SCENARIO 6: Payroll tháng 5/2026 đã được duyệt ─────────────────────────
-- Test: GET /api/payroll/me

INSERT INTO payrolls (
    driver_id, payroll_month, payroll_year,
    base_salary, months_of_service,
    total_revenue, revenue_share_pct, revenue_bonus,
    kpi_bonus, top_driver_bonus, other_bonus,
    insurance_employee, driver_debt_deduction, advance_deduction, other_deduction,
    status
)
SELECT p.id, 5, 2026,
       9000000, 40,
       15000000, 15.00, 2250000,
       500000, 0, 200000,
       900000, 500000, 0, 0,
       'approved'
FROM profiles p JOIN accounts a ON a.id = p.id
WHERE a.email = 'driver1@example.com'
  AND NOT EXISTS (
      SELECT 1 FROM payrolls pw WHERE pw.driver_id = p.id AND pw.payroll_month = 5 AND pw.payroll_year = 2026
  );

-- ─── SCENARIO 7: Salary Advance đang pending ─────────────────────────────────
-- Test: GET /api/payroll/advance, POST /api/payroll/advance

INSERT INTO salary_advances (driver_id, amount, reason, request_month, request_year, status)
SELECT p.id, 2000000, 'Cần tiền đóng học phí cho con', 6, 2026, 'pending'
FROM profiles p JOIN accounts a ON a.id = p.id
WHERE a.email = 'driver1@example.com'
  AND NOT EXISTS (
      SELECT 1 FROM salary_advances sa
      WHERE sa.driver_id = p.id AND sa.request_month = 6 AND sa.request_year = 2026
        AND sa.status IN ('pending', 'approved')
  );

-- ─── SCENARIO 8: KPI tháng 6/2026 (tháng hiện tại) ──────────────────────────
-- Test: GET /api/kpi/me, GET /api/kpi/leaderboard

INSERT INTO kpi_records (driver_id, vehicle_group_id, month, year,
                          completed_shipments, total_revenue, late_deliveries, incident_count)
SELECT p.id, (SELECT id FROM vehicle_groups WHERE price_per_km = 10000),
       6, 2026, 8, 8500000, 0, 0
FROM profiles p JOIN accounts a ON a.id = p.id
WHERE a.email = 'driver1@example.com'
ON CONFLICT (driver_id, month, year) DO NOTHING;

-- KPI driver2 để có leaderboard có 2 người
INSERT INTO kpi_records (driver_id, vehicle_group_id, month, year,
                          completed_shipments, total_revenue, late_deliveries, incident_count)
SELECT p.id, (SELECT id FROM vehicle_groups WHERE price_per_km = 10000),
       6, 2026, 5, 5200000, 1, 0
FROM profiles p JOIN accounts a ON a.id = p.id
WHERE a.email = 'driver2@example.com'
ON CONFLICT (driver_id, month, year) DO NOTHING;

-- ─── SCENARIO 9: Incident đang mở — test GET /api/incidents/my ───────────────

DO $$
DECLARE
    v_arrived_shipment_id INT;
    v_driver2_id INT;
BEGIN
    SELECT p.id INTO v_driver2_id FROM profiles p JOIN accounts a ON a.id = p.id WHERE a.email = 'driver2@example.com';
    SELECT os.id INTO v_arrived_shipment_id
    FROM order_shipments os JOIN orders o ON o.id = os.order_id
    WHERE o.cargo_name = 'Failed Test: Khách từ chối nhận' AND os.shipment_index = 1 LIMIT 1;

    IF v_arrived_shipment_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM incidents WHERE shipment_id = v_arrived_shipment_id
    ) THEN
        INSERT INTO incidents (shipment_id, reported_by, incident_type, severity_level,
                               description, location, status, occurred_at)
        VALUES (v_arrived_shipment_id, v_driver2_id, 'customer_refusal', 'low',
                'Khách hàng không ra nhận hàng sau nhiều lần gọi điện. Đã chờ 30 phút tại điểm giao.',
                '22 Nguyễn Văn Cừ, Q.5, TP.HCM', 'open', NOW() - INTERVAL '30 minutes');
    END IF;
END $$;

-- ─── VALIDATION ───────────────────────────────────────────────────────────────

SELECT 'shipment_payments' AS entity, COUNT(*) AS count FROM shipment_payments
UNION ALL
SELECT 'payment_receipts',  COUNT(*) FROM payment_receipts
UNION ALL
SELECT 'debts (driver)',    COUNT(*) FROM debts WHERE debt_type = 'driver'
UNION ALL
SELECT 'payrolls',          COUNT(*) FROM payrolls
UNION ALL
SELECT 'salary_advances',   COUNT(*) FROM salary_advances
UNION ALL
SELECT 'kpi_records',       COUNT(*) FROM kpi_records
UNION ALL
SELECT 'incidents',         COUNT(*) FROM incidents
UNION ALL
SELECT 'leave_requests',    COUNT(*) FROM leave_requests;

-- ─── SCENARIO: Leave requests tháng 6/2026 ───────────────────────────────────
-- Test: GET /api/leave/me, GET /api/leave/summary
DO $$
DECLARE
    v_driver_id INT;
BEGIN
    SELECT p.id INTO v_driver_id
    FROM profiles p JOIN accounts a ON a.id = p.id
    WHERE a.email = 'driver@example.com';

    IF v_driver_id IS NOT NULL THEN
        -- 1 ngày nghỉ không lương (trừ công)
        INSERT INTO leave_requests (driver_id, leave_date, leave_type, reason, status)
        VALUES (v_driver_id, '2026-06-10', 'unpaid', 'Việc gia đình', 'approved')
        ON CONFLICT (driver_id, leave_date) DO NOTHING;

        -- 1 ngày nghỉ có lương (lễ Giỗ Tổ Hùng Vương 18/04, tháng 4)
        INSERT INTO leave_requests (driver_id, leave_date, leave_type, reason, status)
        VALUES (v_driver_id, '2026-04-18', 'paid', 'Giỗ Tổ Hùng Vương', 'approved')
        ON CONFLICT (driver_id, leave_date) DO NOTHING;
    END IF;
END $$;

-- ============================================================================
-- KPI SEED DATA — Test cho driver KPI screen & leaderboard
-- Chạy sau các seed trên. Tháng 6/2026 = current month, 5/2026, 4/2026
-- ============================================================================

DO $$
DECLARE
    v_driver1_id   INT;
    v_driver2_id   INT;
    v_group_small  INT;
    v_group_medium INT;
BEGIN
    SELECT p.id INTO v_driver1_id FROM profiles p JOIN accounts a ON a.id = p.id WHERE a.email = 'driver1@example.com';
    SELECT p.id INTO v_driver2_id FROM profiles p JOIN accounts a ON a.id = p.id WHERE a.email = 'driver2@example.com';
    SELECT id INTO v_group_small  FROM vehicle_groups WHERE price_per_km = 10000 LIMIT 1;
    SELECT id INTO v_group_medium FROM vehicle_groups WHERE price_per_km = 15000 LIMIT 1;

    -- ── Driver 1: Small Van — tháng 6/2026 (tháng hiện tại) ─────────────────
    INSERT INTO kpi_records (
        driver_id, vehicle_group_id, month, year,
        completed_shipments, total_revenue, late_deliveries,
        incident_count, major_incident_count, critical_incident_count
    ) VALUES (
        v_driver1_id, v_group_small, 6, 2026,
        18, 12600000, 1, 1, 0, 0
    )
    ON CONFLICT (driver_id, month, year) DO UPDATE SET
        completed_shipments = EXCLUDED.completed_shipments,
        total_revenue       = EXCLUDED.total_revenue,
        late_deliveries     = EXCLUDED.late_deliveries,
        incident_count      = EXCLUDED.incident_count;

    -- ── Driver 1: tháng 5/2026 ───────────────────────────────────────────────
    INSERT INTO kpi_records (
        driver_id, vehicle_group_id, month, year,
        completed_shipments, total_revenue, late_deliveries,
        incident_count, major_incident_count, critical_incident_count
    ) VALUES (
        v_driver1_id, v_group_small, 5, 2026,
        22, 15400000, 2, 0, 0, 0
    )
    ON CONFLICT (driver_id, month, year) DO UPDATE SET
        completed_shipments = EXCLUDED.completed_shipments,
        total_revenue       = EXCLUDED.total_revenue,
        late_deliveries     = EXCLUDED.late_deliveries,
        incident_count      = EXCLUDED.incident_count;

    -- ── Driver 1: tháng 4/2026 ───────────────────────────────────────────────
    INSERT INTO kpi_records (
        driver_id, vehicle_group_id, month, year,
        completed_shipments, total_revenue, late_deliveries,
        incident_count, major_incident_count, critical_incident_count
    ) VALUES (
        v_driver1_id, v_group_small, 4, 2026,
        19, 13300000, 0, 0, 0, 0
    )
    ON CONFLICT (driver_id, month, year) DO UPDATE SET
        completed_shipments = EXCLUDED.completed_shipments,
        total_revenue       = EXCLUDED.total_revenue,
        late_deliveries     = EXCLUDED.late_deliveries,
        incident_count      = EXCLUDED.incident_count;

    -- ── Driver 2: Small Van — tháng 6/2026 (cho leaderboard) ────────────────
    INSERT INTO kpi_records (
        driver_id, vehicle_group_id, month, year,
        completed_shipments, total_revenue, late_deliveries,
        incident_count, major_incident_count, critical_incident_count
    ) VALUES (
        v_driver2_id, v_group_small, 6, 2026,
        25, 17500000, 0, 0, 0, 0
    )
    ON CONFLICT (driver_id, month, year) DO UPDATE SET
        completed_shipments = EXCLUDED.completed_shipments,
        total_revenue       = EXCLUDED.total_revenue,
        late_deliveries     = EXCLUDED.late_deliveries,
        incident_count      = EXCLUDED.incident_count;

    -- ── Driver 2: tháng 5/2026 ───────────────────────────────────────────────
    INSERT INTO kpi_records (
        driver_id, vehicle_group_id, month, year,
        completed_shipments, total_revenue, late_deliveries,
        incident_count, major_incident_count, critical_incident_count
    ) VALUES (
        v_driver2_id, v_group_small, 5, 2026,
        20, 14000000, 1, 1, 1, 0
    )
    ON CONFLICT (driver_id, month, year) DO UPDATE SET
        completed_shipments = EXCLUDED.completed_shipments,
        total_revenue       = EXCLUDED.total_revenue,
        late_deliveries     = EXCLUDED.late_deliveries,
        incident_count      = EXCLUDED.incident_count;
END $$;

-- Validate KPI seed
SELECT 'kpi_records inserted' AS check, COUNT(*) AS total FROM kpi_records;
SELECT driver_id, month, year, completed_shipments, total_revenue::text, on_time_rate::text
FROM kpi_records ORDER BY driver_id, year DESC, month DESC;
