-- NÂNG CẤP DB ĐÃ DEPLOY (KHÔNG MẤT DỮ LIỆU)
-- Gộp mọi thay đổi schema tháng 7/2026. Idempotent: chạy lại nhiều lần vẫn an toàn.
-- KHÔNG dùng file này cho DB mới — DB mới dùng "DB script.sql".

BEGIN;

-- 1. Expenses: 5 loại + luồng duyệt
UPDATE expenses SET expense_type = 'repair' WHERE expense_type = 'minor_repair';
UPDATE expenses SET expense_type = 'other'  WHERE expense_type = 'ferry';
ALTER TABLE expenses DROP CONSTRAINT IF EXISTS expenses_expense_type_check;
ALTER TABLE expenses ADD CONSTRAINT expenses_expense_type_check
    CHECK (expense_type IN ('toll','parking','etc','fuel','repair','maintenance','depreciation','other'));
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'approved';
ALTER TABLE expenses DROP CONSTRAINT IF EXISTS expenses_status_check;
ALTER TABLE expenses ADD CONSTRAINT expenses_status_check
    CHECK (status IN ('pending','approved','rejected'));
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS reviewed_by   INT REFERENCES profiles(id);
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS reviewed_at   TIMESTAMPTZ;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS reject_reason TEXT;

-- 2. Maintenance: driver gửi yêu cầu bảo dưỡng
ALTER TABLE maintenance_records DROP CONSTRAINT IF EXISTS maintenance_records_status_check;
ALTER TABLE maintenance_records ADD CONSTRAINT maintenance_records_status_check
    CHECK (status IN ('requested','open','pending_verification','completed','rejected'));
ALTER TABLE maintenance_records ADD COLUMN IF NOT EXISTS requested_by   INT REFERENCES profiles(id);
ALTER TABLE maintenance_records ADD COLUMN IF NOT EXISTS request_reason TEXT;
ALTER TABLE maintenance_records ADD COLUMN IF NOT EXISTS reject_reason  TEXT;

-- 3. Lịch sử gán xe
CREATE TABLE IF NOT EXISTS vehicle_driver_assignments (
    id                  INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    vehicle_id          INT NOT NULL REFERENCES vehicles(id),
    driver_id           INT REFERENCES profiles(id),
    previous_driver_id  INT REFERENCES profiles(id),
    action              TEXT NOT NULL CHECK (action IN ('assign','unassign')),
    note                TEXT,
    created_by          INT REFERENCES profiles(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Ledger: đủ 15 event
ALTER TABLE financial_transactions DROP CONSTRAINT IF EXISTS financial_transactions_event_type_check;
ALTER TABLE financial_transactions ADD CONSTRAINT financial_transactions_event_type_check
    CHECK (event_type IN (
        'shipment_revenue','prepaid_received','prepaid_refunded',
        'cash_receipt','bank_receipt',
        'driver_debt_created','driver_debt_paid',
        'customer_debt_created','customer_payment',
        'pass_through_cost','expense_recorded',
        'payroll_paid','bonus_paid',
        'advance_disbursed','advance_recovered'
    ));

-- 5. Ngày lễ hưởng 200% lương
CREATE TABLE IF NOT EXISTS company_holidays (
    holiday_date DATE PRIMARY KEY,
    name         TEXT NOT NULL
);
INSERT INTO company_holidays (holiday_date, name) VALUES
    ('2026-01-01', 'Tết Dương lịch'),
    ('2026-02-17', 'Tết Âm lịch (mùng 1)'),
    ('2026-02-18', 'Tết Âm lịch (mùng 2)'),
    ('2026-02-19', 'Tết Âm lịch (mùng 3)'),
    ('2026-04-26', 'Giỗ Tổ Hùng Vương (10/03 ÂL)'),
    ('2026-04-30', 'Ngày Giải phóng miền Nam'),
    ('2026-05-01', 'Ngày Quốc tế lao động'),
    ('2026-09-02', 'Ngày Quốc khánh')
ON CONFLICT (holiday_date) DO NOTHING;

-- 6. KPI số chuyến lẻ (chia doanh thu khi điều chuyển) — cần dựng lại view phụ thuộc
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'kpi_records' AND column_name = 'completed_shipments'
          AND data_type IN ('integer','smallint','bigint')
    ) THEN
        DROP VIEW IF EXISTS v_leaderboard;
        ALTER TABLE kpi_records
            ALTER COLUMN completed_shipments TYPE NUMERIC(8,1)
            USING completed_shipments::numeric;
    END IF;
END $$;

CREATE OR REPLACE VIEW v_leaderboard AS
SELECT
    k.vehicle_group_id,
    vg.name                     AS vehicle_group_name,
    k.year,
    k.month,
    k.driver_id,
    p.full_name                 AS driver_name,
    k.completed_shipments,
    k.total_revenue,
    k.incident_count,
    RANK() OVER (
        PARTITION BY k.vehicle_group_id, k.year, k.month
        ORDER BY k.total_revenue DESC
    )                           AS revenue_rank,
    RANK() OVER (
        PARTITION BY k.vehicle_group_id, k.year, k.month
        ORDER BY k.completed_shipments DESC
    )                           AS trips_rank
FROM kpi_records k
JOIN profiles p       ON p.id  = k.driver_id
JOIN vehicle_groups vg ON vg.id = k.vehicle_group_id;

-- 7. Bảng chia doanh thu (nếu DB cũ chưa có — code cũng tự tạo lazy)
CREATE TABLE IF NOT EXISTS shipment_revenue_allocations (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id         INT NOT NULL REFERENCES order_shipments(id) ON DELETE CASCADE,
    driver_id           INT NOT NULL REFERENCES profiles(id),
    share_percent       NUMERIC(5,2) NOT NULL CHECK (share_percent > 0 AND share_percent <= 100),
    allocation_reason   TEXT NOT NULL
                            CHECK (allocation_reason IN ('default_owner','incident_full_transfer','incident_split')),
    incident_id         INT REFERENCES incidents(id) ON DELETE SET NULL,
    created_by          INT REFERENCES profiles(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (shipment_id, driver_id)
);

-- 7b. Bút toán đảo + hủy xác nhận thanh toán
ALTER TABLE financial_transactions ADD COLUMN IF NOT EXISTS reversal_of_id BIGINT REFERENCES financial_transactions(id);
ALTER TABLE financial_transactions ADD COLUMN IF NOT EXISTS reversal_reason TEXT;
CREATE INDEX IF NOT EXISTS idx_ftx_reversal_of ON financial_transactions(reversal_of_id) WHERE reversal_of_id IS NOT NULL;
ALTER TABLE debt_payments DROP CONSTRAINT IF EXISTS debt_payments_status_check;
ALTER TABLE debt_payments ADD CONSTRAINT debt_payments_status_check
    CHECK (status IN ('pending','confirmed','rejected','voided'));

-- 8. Index hiệu năng
CREATE INDEX IF NOT EXISTS idx_expenses_status          ON expenses(status);
CREATE INDEX IF NOT EXISTS idx_maintenance_requested    ON maintenance_records(status) WHERE status = 'requested';
CREATE INDEX IF NOT EXISTS idx_vda_vehicle              ON vehicle_driver_assignments(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_vda_driver               ON vehicle_driver_assignments(driver_id);
CREATE INDEX IF NOT EXISTS idx_vda_prev_driver          ON vehicle_driver_assignments(previous_driver_id);
CREATE INDEX IF NOT EXISTS idx_rev_alloc_shipment       ON shipment_revenue_allocations(shipment_id);
CREATE INDEX IF NOT EXISTS idx_rev_alloc_driver         ON shipment_revenue_allocations(driver_id);
CREATE INDEX IF NOT EXISTS idx_debts_order_id           ON debts(order_id);
CREATE INDEX IF NOT EXISTS idx_debt_payments_debt_status ON debt_payments(debt_id, status);
CREATE INDEX IF NOT EXISTS idx_debt_payments_pending    ON debt_payments(status) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_sreceipts_orr_id         ON shipment_receipts(order_receipt_request_id);
CREATE INDEX IF NOT EXISTS idx_shipments_completed_at   ON order_shipments(completed_at) WHERE status = 'completed';

COMMIT;
