-- =====================================================================
-- 20260801_driver_group_history
-- Lịch sử đổi nhóm xe cố định của tài xế.
--
-- Vì sao cần: đổi nhóm quyết định ngưỡng thưởng vượt KPI (50/65/70/100 triệu tuỳ
-- nhóm) và quyết định tài tranh giải "lái xe xuất sắc" ở bảng nào — tức là đụng
-- thẳng vào tiền. Trước đây chỉ UPDATE drivers, không lưu lại gì: không biết ai
-- đổi, đổi lúc nào, từ nhóm nào sang nhóm nào, có kéo theo KPI kỳ nào không.
--
-- An toàn với dữ liệu cũ: chỉ THÊM bảng mới, không đụng bảng nào đang có.
-- Chạy lại nhiều lần không sao (idempotent).
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS driver_vehicle_group_history (
    id                    INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100000 INCREMENT BY 1) PRIMARY KEY,
    driver_id             INT NOT NULL REFERENCES profiles(id),
    from_vehicle_group_id INT REFERENCES vehicle_groups(id),
    to_vehicle_group_id   INT NOT NULL REFERENCES vehicle_groups(id),
    changed_by            INT NOT NULL REFERENCES profiles(id),
    reason                TEXT,
    -- Các kỳ KPI đã được cập nhật theo nhóm mới, dạng "7/2026, 8/2026".
    -- Rỗng nghĩa là không kỳ nào (lương đều đã chốt) → nhóm mới chỉ áp dụng từ kỳ sau.
    applied_periods       TEXT,
    kpi_synced            BOOLEAN NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dvgh_driver ON driver_vehicle_group_history(driver_id, created_at DESC);

INSERT INTO schema_migrations (filename)
VALUES ('20260801_driver_group_history.sql')
ON CONFLICT (filename) DO NOTHING;

COMMIT;
